### ISSUE TITLE
Can't move an infix term

### ISSUE THREAD

**Issue by stacycurl** [unisonweb/unison#800] opened 2019-09-17 10:47 UTC
```
.> move.term base.Text.++ ++

  InvalidWordyId ""
```

**Comment by aryairani** [comment] 2019-09-17 15:07
Oof, sorry about this @stacycurl, and thanks for reporting.  That said, I’m going to close it as a duplicate of #763, which we should make a priority.

**Closed by aryairani** 2019-09-17 15:07 UTC

**Comment by stacycurl** [comment] 2019-09-17 15:22
Oops, sorry, I looked for an existing bug, but I must have missed it.

**Comment by aryairani** [comment] 2019-09-17 17:00
@stacycurl No worries, thanks for reporting.
