### ISSUE TITLE
`merge.squash` command

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1465] opened 2020-04-25 16:50 UTC
Behavior is it just overlays the two trees, not trying to do anything with history, and no need to compute LCA. This would typically be how I'd like to merge a PR that is just new definitions. 

Right now, just doing builtin.merge takes like a full minute on base, since it ends up scanning all the way back to the beginning of time to realize that the LCA is literally the empty namespace :) I think longer term we should have some indexing structure in the repoformat to make LCA calculations log time, but `merge.squash` solves the problem and is IMO independently useful. 

You can kinda sorta get this using `find` and `copy` commands but it's too many steps / kind of janky.

/cc @dolio

**Comment by aryairani** [comment] 2020-04-28 20:08
At a glance, I hate this. 😁 I'm 100% in support of having everything be fast & not too many steps though.  Can we join forces to discuss and possibly brainstorm alternatives?  Let's figure out why `git merge` typically doesn't take minutes.

Side note: I don't recommend doing `builtin.merge` on base; it's kind of coincidence IMO that it creates the names you want.  Although also not great, I'd recommend creating individual aliases (perhaps scripted in a text editor) for the few names you actually want to create, e.g. `alias.term ##Nat.complement Nat.complement` rather than create 100 and find/copy out 6.  I understand that the problem is more general than `builtin.merge` though, so we should still address it.

**Comment by dolio** [comment] 2020-04-28 21:25
I searched briefly when I first got pinged on this, and there are data structures for doing LCA on trees in constant time (I imagine DAGs aren't much worse if at all). I think the problem is that the algorithm for LCA in unison is to just search the entire graph. Someone needs to build the data structure for computing it efficiently.

**Comment by pchiusano** [comment] 2020-04-28 23:54
Git doesn't have this problem since it is never merging unrelated trees, but I don't think their LCA calculation does anything fancy, it's just typically merging trees whose LCA is pretty "close". We could do the git thing if we recorded the first hash after the empty namespace and associated that with each namespace. If that differs, there's no LCA and no need to scan history. This would require a repoformat change though.

Even if LCA were always fast, I still want this because I want a way to discard history for a whole namespace. I just don't care about the history sometimes, sometimes it's screwed up, sometimes it's actively wrong (I started with namespace X and then deleted a bunch of stuff... but I don't want those deletions to show up when merging). Yeah you can discard the history with a combination of commands, sort of (it misses patches), but it's not great.

Seems like a perfectly cromulent operation, what say you @aryairani ?? :) Maybe call it something else without merge in the name?

**Comment by aryairani** [comment] 2020-04-29 16:11
> Git doesn't have this problem since it is never merging unrelated trees

Hmm.  I didn't believe this, so I checked out `scala/scala` (34,732 commits) and `git/git` (59,126 commits), which have unrelated histories.  When I tried to merge them together, it took git 1.017s  to determine this, and bail with `refusing to merge unrelated histories`.  When I passed `--allow-unrelated-histories`, it took 2.746s to complete the merge (which I assume included 1.017s of trying to find an LCA and 1.164s of decompressing files).

So if you are waiting more than 1s for LCA search in `unisonweb/base`, which has a total of 1,976 namespace files (meaning that the number of those that were part of the history of `.` was less or much less), then I think `git` is doing something much better/smarter/faster than `ucm` is.

> We could do the git thing if

What is the git thing?

> Even if LCA were always fast, I still want this.
> Maybe call it something else without merge in the name?

\<nod> I was trying to come up with an alternative name yesterday, but didn't get very far. 
 `copy.namespace`? Just came up with that right now.  `copy.recursive`?  `copy.all.definitions.together.sometimes.resulting.in.name.conflicts.except.patches.are.a.special.case.and.get.merged.ps.any.deletions.are.silently.lost`? :)

The main thing I want to avoid is us and others defaulting to using this command instead of merge, which I think would be equivalent to the buggy merge we had before we implemented 3-way.

I still suspect there's something tidier we could do, but in the absence of a counter-proposal, if you wanna create a `copy.namespace` that does a historically-shallow merge of the source into a new node at the dest, and we just ¯\\\_(ツ)_/¯ at whatever it ends up doing with patches, I'd be pretty okay with that.  😄

**Comment by pchiusano** [comment] 2020-04-29 23:15
Cool. I’ll noodle on it and maybe implement something.

Those are interesting numbers from git and looks like I was mistaken about it having any sort of short circuit for unrelated histories! 

I’m actually still not sure git is doing anything fancy or if it’s just good constant factors. Like you could get a long way by not having to to do all the deserialization at every step, just the naive algo on a graph of just the hashes.

**Comment by aryairani** [comment] 2020-04-30 01:41
If you want to scale back the deserialization at every step, check out `getCausal00` in `V1.hs` — we could try to find a way to make it available in the spot it's needed.

**Comment by pchiusano** [comment] 2020-05-01 11:14
Ooh good idea.

**Closed** 2020-05-22 03:23 UTC
Labels: namespace-merge
