### ISSUE TITLE
renaming terms + pretty-printing can cause aliasing

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2131] opened 2021-06-18 02:04 UTC
Speaking of [how to pretty print](https://github.com/unisonweb/unison/issues/2110#issuecomment-863669428), check this out:

```haskell
foo y =
  if y > 10 then 999 else
    bar x = x + 1
    foo (bar y)

> foo 3
  ⧩
  999
```

```
.tmp.aliasing> add
.tmp.aliasing> rename foo bar
.tmp.aliasing> edit bar
```

```haskell
bar : Nat -> Nat
bar y =
  use Universal >
  if y > 10 then 999
  else
    bar x =
      use Nat +
      x + 1
    bar (bar y)

> bar 3
  ⧩
  5
```

**Comment by aryairani** [comment] 2021-06-18 03:46
`bar` should probably render as:
```haskell
bar : Nat -> Nat
bar y =
  use Universal >
  if y > 10 then 999
  else
    bar x =
      use Nat +
      x + 1
    bar#4rp4 (bar y)

> bar 3
```

which means pretty-printing names for a definition requires knowing what shadowing symbols are in scope; /cc #2110

**Comment by pchiusano** [comment] 2021-06-18 04:11
Dupe of https://github.com/unisonweb/unison/issues/525 which also proposes a fix that seems straightforward to do, but we just never got around to it. 😬

**Closed as completed by pchiusano** 2021-06-18 04:11 UTC

**Comment by pchiusano** [comment] 2021-06-18 04:25
... also since this was tagged in #2110, I just want to mention that the PPE can continue to be naive and unaware of any local name bindings. 

The pretty-printer can do the alpha renaming to avoid accidental capture, as suggested in https://github.com/unisonweb/unison/issues/525#issuecomment-506193614.

**Comment by aryairani** [comment] 2021-06-18 22:57
Great!
