### ISSUE TITLE
Speed of searches in the UI slows right down with more things in the codebase

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#2109] opened 2021-06-12 16:06 UTC
I type `either fold` into the codebase UI 'find' dialog - here's how long I have to wait to see results:

1) with only `base` in my codebase:  <1 second
2) same as 1, plus also a recent base PR: 8 seconds
3) same as 2, plus also a pull of (the root of) unison_random_mersenne: 23 seconds

What's going wrong?  (Could it be a function of hidden history also being pulled in?)

This is in a freshly inited v2 codebase using M2.  And note I'm actually counting spins of the UI find dialog spinner rather than seconds...  

Commands to replicate each step:

1) `pull https://github.com/unisonweb/base:.releases._M2 .base`
2) `pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/pchiusano/unisoncode:.prs.random2`  (taken from the PR [here](https://github.com/unisonweb/base/issues/12))
3) `pull https://github.com/atacratic/unison-random-mersenne` (which now has a `.unison/v2`)

Just clicking to view terms found in the left-hand pane is also slow: 9 seconds in case (3) above.

**Comment by runarorama** [comment] 2021-06-12 16:27
I'm working on this issue at the moment. The problem is that the UI is stateless so it doesn't cache anything between requests, including the branch contents and the PPE. These are expensive to compute.

**Comment by pchiusano** [comment] 2021-06-12 16:48
It is known that search time depends on the total number of definitions with names, and @runarorama has a WIP that should help. That said I think something silly must be happening for it to be this slow.

**Comment by hojberg** [comment] 2021-08-16 20:07
Closing as I think this is basically a dupe of #2045

**Closed as completed by hojberg** 2021-08-16 20:07 UTC
Labels: performance, codebase-server, codebase-ui, to-discuss, E16, R3, I3, C1
