### ISSUE TITLE
Url links inside parenthetical statements are not interpreted as such

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#4633] opened 2024-01-23 23:49 UTC
If you create a standard url link inside a parenthetical statement, the links may not be rendered as actual links. 

For example the following doc block will fail to interpret the first link as a valid link: 

```
docRepro = {{
  Link link link blah ([myLink](www.google.com), [anotherLink](www.google.com))
}}
```
![Screen Shot 2024-01-23 at 3 41 36 PM](https://github.com/unisonweb/unison/assets/7613551/9d150692-9144-4610-b659-99d7ffc17e9a)

If the parenthetical is not immediately started with a link, you are able to successfully incorporate url links: 

```
linkNotAtBeginning = {{
  Text text blah (something something [myLink](www.google.com) blah blah blah)
}}
```

A transcript is attached with the doc code capable of producing the issue, but the issue is best seen in the local ui or unison share.

[parentheticalLink.md](https://github.com/unisonweb/unison/files/14030873/parentheticalLink.md)

**Comment by andreystepanov** [comment] 2024-02-06 11:10
Here's another example of similar issue, where parser fails to understand braces `(` `)` in `URL`s.

Live example of `Bytes.flatten.doc` in `base` library:

https://share.unison-lang.org/@unison/base/code/releases/2.12.0/latest/terms/Bytes/flatten

![shot-2024-02-06-at-12-56-55--area](https://github.com/unisonweb/unison/assets/472885/74056073-6bdd-47ca-bf3a-0da741315c13)

Where `rope` link defined as:

```markdown
[rope](https://en.wikipedia.org/wiki/Rope_(data_structure))
```

Parser need to be smarter about certain cases or `URL`s.
`(` and `)` is totally valid characters in `URL` and doesn't need to be `URL`-encoded.

But i understand that it might be difficult to implement in the parser, which looks for closing `)` while parsing links.

**Comment by andreystepanov** [comment] 2024-02-06 11:20
Meanwhile i fixed doc link via contribution, by using `%28`/`%29` encoded braces.

https://share.unison-lang.org/@unison/base/contributions/15

**Comment by andreystepanov** [comment] 2024-02-06 11:32
Instead of dealing with markdown parser for links, maybe we can just extend `Doc` data-type:

```unison
unique type Doc
  = ...
  | Link Doc Doc
  | ...
  | ...
```

This way it might be easier to link images and other kind of documentation elements too.

**Comment by sellout** [comment] 2024-07-09 06:57
Duplicate of #2483.

**Closed as not planned by sellout** 2024-07-09 06:57 UTC
Labels: {{docs}}
