### ISSUE TITLE
Parenthesis ignored when defining ability type signature

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#1675] opened 2020-09-11 00:06 UTC
I've had trouble trying to define a handler which returns a function:

    ability Bar where fun : Nat -> (Nat -> Nat)

produces:

     ability Bar where fun : Nat -> Nat ->{Bar} Nat

but should produce:

     ability Bar where fun : Nat ->{Bar}(Nat -> Nat)

**Comment by anovstrup** [comment] 2020-09-11 01:55
I'm not sure this is a bug. Owing to right-associativity, `ability Bar where fun : Nat -> Nat -> Nat` appears to be treated the same as `ability Bar where fun : Nat -> (Nat -> Nat)`—both are interpreted as `ability Bar where fun : Nat -> (Nat ->{Bar} Nat)`, following the default that the ability is only needed for the final `->`.  In cases where that default is inapplicable, I think you've got to explicitly label the arrow that requires the ability (e.g., `ability Bar where fun : Nat ->{Bar} Nat -> Nat`). It's not obvious that interpreting explicit vs elided parentheses differently would lead to less confusion than the current behavior.

**Comment by pchiusano** [comment] 2020-09-22 20:37
Going to close this one as "as designed" (the parentheses are invisible to the parser and I don't really want to mess with that) but I think the language reference could use a note on the limitations of the algorithm for adding the ability braces to the signatures: https://www.unisonweb.org/docs/language-reference#user-defined-abilities-1

Something like: "If the rightmost function arrow of the signature doesn't have an attached `{}`, one will be added automatically. For example, in the type `ability Stream v where emit : v -> ()`, the rightmost arrow of `emit` is `v -> ()`. Since it does not have ability braces, they are implicitly added: `emit : v ->{Stream v} ()`.

**Closed as completed by pchiusano** 2020-09-22 20:37 UTC
