### ISSUE TITLE
base.Nat.msb.test fails with new runtime

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#2082] opened 2021-06-06 19:45 UTC
I pulled the (v2) base, then did Arya's trick to blow away cached test results (`sqlite3 ~/.unison/v2/unison.sqlite3 "delete from watch_result; delete from watch;"`), then tried to run the base tests, but hit a call to `builtin.bug`.  By repeated experimentation I found that the test triggering the problem was `Nat.msb.test`.

I've jumped to the conclusion that this is something that has always been broken with the new runtime, but with the problem being masked by a cached test result from the old runtime.  Guess that could be wrong though.  

```
.base_v2.Nat.msb> test

  ✅  


  💔💥
  
  I've encountered a call to builtin.bug with the following value:
  
    ("The values being compared are not equal",
    ._base.prs._2.Optional.Some 0,
    ._base.prs._2.Optional.Some 63)
  
  I'm sorry this message doesn't have more detail about the location of the failure. My makers plan
  to fix this in a future release. 😢


    New test results:
  
  😶 No tests available.

```

Incidentally:
- when tests fail with a builtin.bug or crash, it's painful to work out which test caused the failure, because that info is not printed to screen
- I would suggest having a nightly/weekly run where the test cache on a copy of the unison share codebase is blown away, and all the tests rerun, checking that they produce the same output as with the original cache in place.  That will defend against regressions in the runtime, and also make it more feasible to add extra checking/policing of correctness to the runtime.  Otherwise latent problems could build up as hidden failures in people's tests, and erode people's faith in the test caching idea.  

This was with the M2 release candidate from 4-Jun, and the v2 base library as of 6-Jun.

**Comment by pchiusano** [comment] 2021-06-07 20:03
Good catch. @dolio can you take a look? It looks like `Nat.msb` might just be wrong. 

We should definitely have CI run all the tests in base after a cache clear, tracking that here https://github.com/unisonweb/unison/issues/2088

**Comment by pchiusano** [comment] 2021-06-07 20:16
Also https://github.com/unisonweb/unison/issues/2089

**Comment by dolio** [comment] 2021-06-07 20:43
I think this is the same bug as #2083. `msb` is a loop that uses inequality.

**Comment by pchiusano** [comment] 2021-06-07 20:47
Ah, I was confused, I thought this was a builtin. @atacratic could you do a PR against base that uses `Nat.gt` here instead?

**Comment by pchiusano** [comment] 2021-06-08 13:20
Going to close this as a dupe of #2083

**Closed as completed by pchiusano** 2021-06-08 13:20 UTC
