### ISSUE TITLE
ucm runtime crash when running a function

### ISSUE THREAD

**Issue by etorreborre** [unisonweb/unison#1489] opened 2020-04-30 09:01 UTC
I don't know how to minimize the example but maybe the error message will be enough to track the issue. Here's my code:
```
ability Stream e where
  emit : e ->{Stream e} ()

Stream.range : Nat -> Nat -> {Stream Nat} ()
Stream.range n m =
  if n >= m then ()
  else
    emit n
    Stream.range (n + 1) m

Stream.toList : '{Stream a} () -> [a]
Stream.toList stream =
  h : [a] -> Request {Stream a} () -> [a]
  h acc = cases
    {Stream.emit e -> resume} ->
      handle resume () with h (acc ++ [e])
    {u} -> acc
  handle !stream with h []

Stream.foldLeft : (b -> a -> b) -> b -> '{Stream a} () -> b
Stream.foldLeft f b stream =
  go : b -> Request {Stream a} () -> b
  go b' = cases
    {emit a -> resume} -> handle (resume ()) with go (f b' a)
    {u} -> b'

  handle !stream with go b

Stream.sum : '{Stream Nat} () -> Nat
Stream.sum = Stream.foldLeft (+) 1

ability Ask a where
  ask : a

Ask.provide : a -> '{Ask a,e} r -> '{e} r
Ask.provide a asker =
  h = cases
    {r}                 -> r
    {Ask.ask -> resume} -> (handle resume a with h)
  '(handle !asker with h)

use Ask ask

Stream.pipe : '{Ask a, Stream b} () -> '{Stream a} () -> '{Stream b} ()
Stream.pipe output input =
  handle !output with cases
    {u} -> 'u
    {emit b -> k} ->
      '(emit b)
      k
    {Ask.ask -> k1} ->
      handle !input with cases
        {u} -> 'u
        {emit a -> k} ->
          Stream.pipe '(k1 a) k


Stream.map : (a -> b) -> '{Stream a} () -> '{Stream b} ()
Stream.map f s =
  go : (a -> b) -> {Ask a, Stream b} ()
  go f = emit (f ask)
  Stream.pipe '(go f) s

--> '(Stream.range 1 10)
> Stream.toList ('(Stream.range 1 10))
> Stream.map (n -> n+1) '(Stream.range 1 10)
```
The last `Stream.map` exits `ucm` with 
```
ucm: ./Data/Vector/Generic/Mutable.hs:691 (read): index out of bounds (-1,0)
CallStack (from HasCallStack):
  error, called at ./Data/Vector/Internal/Check.hs:87:5 in vector-0.12.0.3-LfvlcMFJAcY18uD1Y2O5Ig:Data.Vector.Internal.Check
```

**Comment by pchiusano** [comment] 2020-04-30 13:20
@etorreborre The last `map` there is returning a function / delayed computation, which it is attempting to decompile back to a term and print out. The decompilation of functions is pretty janky at the moment (will be more robust with the new runtime we are hoping to merge soon). To avoid the bug, wrap the `Stream.map` in `Stream.toList`. For now I'd avoid trying to have watch expressions that return functions.

I strongly suspect a duplicate of: https://github.com/unisonweb/unison/issues/821 going to close but this will remain linked so we can check this example later.

Also wanted to link this issue: https://github.com/unisonweb/unison/issues/1185 which often results in needing more type annotations than you should when writing handlers. 

Lastly, here's the "official" answers for `pipe` (SPOILER): https://www.unisonweb.org/docs/abilities/#answers

**Closed by pchiusano** 2020-04-30 13:20 UTC
Labels: crash, runtime

**Comment by etorreborre** [comment] 2020-05-01 07:55
Thanks Paul. I left some follow-up questions on Slack but I think I'm facing issues related to #1185
