### ISSUE TITLE
ucm exits when autocompleting path arg for push command

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1282] opened 2020-02-27 19:16 UTC
```
.> push file:///Users/arya/unison4/repo/ t20:15 ~/unison4 (master)$ 
```

**Comment by pete-ts** [comment] 2020-03-21 17:46
I cannot tell if this is a duplicate of https://github.com/unisonweb/unison/pull/1374 :thinking: , but I think so.

**Comment by aryairani** [comment] 2020-03-21 23:49
Oops!  I was wondering where I had put this. :)

**Closed** 2020-03-21 23:49 UTC
Labels: crash, help wanted
