### ISSUE TITLE
TODO - don't know how to compile this term

### ISSUE THREAD

**Issue by jdevuyst** [unisonweb/unison#873] opened 2019-10-17 13:26 UTC
I entered `baz x = x - 1` in a scratch file and then I got this error:

```
    ⍟ These new definitions are ok to `add`:
    
      baz : base.Nat -> base.Int
   
  Now evaluating any watch expressions (lines starting with `>`)...
  Ctrl+C cancels.


  💔💥
  
  I stopped evaluation after encountering an error:
  
    TODO - don't know how to compile this term:
    #m7uplgfko9
    CallStack (from HasCallStack):
      error, called at src/Unison/Runtime/IR.hs:483:10 in unison-parser-typechecker-0.1-GhEsNfzP1hn5VAyhpU4Q65:Unison.Runtime.IR
```

Note that this seems to only happen after pulling in the base library. Otherwise the editor complains that it doesn't know what `-` is.

**Comment by noahhaasis** [comment] 2019-10-17 15:36
It looks like a problem with the typechecker. It inferes type `Nat -> Nat -> Nat` for `-` but `Int` for `1`.

```haskell
i : builtin.Nat
i = 1

baz : builtin.Nat -> builtin.Nat
baz x = x - 1
```

![Bildschirmfoto 2019-10-17 um 17 32 34](https://user-images.githubusercontent.com/26230013/67024113-271ebd80-f104-11e9-8111-0b0c4c641e60.png)

Without the type declaration for `baz` it compiles and fails.

**Comment by pchiusano** [comment] 2019-10-17 19:24
Thanks for reporting @jdevuyst and @noahhaasis, that is a good clue.

**Comment by pchiusano** [comment] 2019-10-17 19:47
I don't think it's an issue with the typechecker. The `base` library has a version of `-` that works on `Nat` and returns an `Int`:

```
  (base.Nat.-) : base.Nat -> base.Nat -> base.Int
  (base.Nat.-) = base.Nat.sub
```

You can also call `Nat.sub` directly.

This seems to be a regression someplace else. A good clue is that I had an old version of topic/reflog checked out which I just happened to try it on but could not reproduce there, but I can reproduce in current master. I'd probably start by bisecting.

**Comment by jdevuyst** [comment] 2019-10-18 16:44
The issue appears to have been introduced in 86e82a6faacf90f4c72d69679a903c97541bae3a

**Comment by aryairani** [comment] 2019-10-18 17:34
@jdevuyst Oof, thank you for tracking that down.

**Comment by aryairani** [comment] 2019-10-18 18:00
I've reverted the commit that @jdevuyst identified as introducing the bug.

To close this issue, would someone please create a test for this case.

**Closed** 2019-10-19 16:19 UTC
Labels: bug, help wanted
