### ISSUE TITLE
some issue with `edit` in transcripts.

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#5169] opened 2024-07-01 15:03 UTC
**Describe and demonstrate the bug**

An `edit` seems to suppress a following `unison` block:

Input:
````
```ucm:hide
scratch/bad> builtins.mergeio lib.builtins
```

```unison
a = 1
```

```ucm
scratch/bad> add
scratch/bad> edit a
```

An `edit` seems to suppress a following `unison` block:
```unison
b = 2
```
^ An empty `ucm` block is produced here

```ucm:error
scratch/bad> add
scratch/bad> view b
```

i.e. "Sorry, I'm still hung up on `a`!"


Without the `edit`, it works as expected:

```ucm:hide
scratch/ok> builtins.mergeio lib.builtins
```

```unison
a = 1
```

```ucm
scratch/ok> add
```

No `edit`, no problem.
```unison
b = 2
```

```ucm
scratch/ok> add
scratch/ok> view b
```
````

Output:
```unison
a = 1
```

```ucm

  Loading changes detected in scratch.u.

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      a : Nat

```
```ucm
scratch/bad> add

  ⍟ I've added these definitions:
  
    a : Nat

scratch/bad> edit a

  ☝️
  
  I added 1 definitions to the top of scratch.u
  
  You can edit them there, then run `update` to replace the
  definitions currently in this namespace.

```
```unison:added-by-ucm scratch.u
a : Nat
a = 1
```

An `edit` seems to suppress a following `unison` block:
```unison
b = 2
```

```ucm

```
^ An empty `ucm` block is produced here

```ucm
scratch/bad> add

  ⊡ Ignored previously added definitions: a

scratch/bad> view b

  ⚠️
  
  The following names were not found in the codebase. Check your spelling.
    b

```
i.e. "Sorry, I'm still hung up on `a`!"

Without the `edit`, it works as expected:

```unison
a = 1
```

```ucm

  Loading changes detected in scratch.u.

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      a : Nat

```
```ucm
scratch/ok> add

  ⍟ I've added these definitions:
  
    a : Nat

```
No `edit`, no problem.
```unison
b = 2
```

```ucm

  Loading changes detected in scratch.u.

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      b : Nat

```
```ucm
scratch/ok> add

  ⍟ I've added these definitions:
  
    b : Nat

scratch/ok> view b

  b : Nat
  b = 2

```

**Environment (please complete the following information):**
ucm 0.5.23

**Comment by aryairani** [comment] 2024-09-30 20:37
I just ran into this again; I'm not sure of what a workaround would be yet.

**Comment by aryairani** [comment] 2024-10-01 04:12
@sellout Might be an easy fix in the transcript parser?

**Comment by sellout** [comment] 2024-10-01 07:54
Making sure I understand exactly what’s happening here.

Given the right context,
````markdown
```ucm
scratch/bad> add
scratch/bad> edit a
```

An `edit` seems to suppress a following `unison` block:
```unison
b = 2
```
^ An empty `ucm` block is produced here
````
results in
````markdown
``` ucm
scratch/bad> add

  ⍟ I've added these definitions:
  
    a : Nat

scratch/bad> edit a

  ☝️
  
  I added 1 definitions to the top of scratch.u
  
  You can edit them there, then run `update` to replace the
  definitions currently in this namespace.

```
``` unison:added-by-ucm scratch.u
a : Nat
a = 1
```

An `edit` seems to suppress a following `unison` block:

``` unison
b = 2
```

``` ucm

```
^ An empty `ucm` block is produced here
````
I see the empty `ucm` block, but I don’t see what’s suppressed.

I’m pretty sure the empty block is produced by https://github.com/unisonweb/unison/blob/3327c8a95c596293425ec4af33436a545567d2f1/unison-cli/src/Unison/Codebase/Transcript/Runner.hs#L312-L319

**Comment by sellout** [comment] 2024-10-01 08:05
Oh, I think I see – the empty `ucm` block should contain something like
```

  Loading changes detected in scratch.u.

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      b : Nat

```
so what’s suppressed is the processing of the preceding `unison` block, not the block itself.

**Comment by sellout** [comment] 2024-10-03 03:47
I think this is a duplicate of #4598.

**Closed as not planned by sellout** 2024-10-03 03:47 UTC
Labels: bug, transcripts
