### ISSUE TITLE
can't include Scope.run in a Doc

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#5098] opened 2024-06-17 15:46 UTC
Input:
````

```unison
> {{ {Scope.run} }}
```
````

Output:
````

  I found a value  of type:  (Unit ->{g1, Scope s1} r) ->{g1} r
  where I expected to find:  (Unit ->{g, Scope s} 𝕩) -> 𝕣
  
      2 | > {{ {Scope.run} }}
  ````

**Comment by pchiusano** [comment] 2024-06-17 15:52
Dupe of #3499

**Closed as completed by pchiusano** 2024-06-17 15:52 UTC
Labels: bug
