### ISSUE TITLE
don't use `less` for typechecking output

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1027] opened 2019-12-06 22:40 UTC
(i.e. commands that are initiated externally/without focus)

**Comment by atacratic** [comment] 2019-12-06 23:32
We'd still want a way to view it with less though, right? Maybe that's the same command as the 'preview add/update' command that people requested (`load`?)

**Comment by anovstrup** [comment] 2019-12-13 03:07
I didn't quite understand this one. What's the real problem it's trying to address?

I've had the experience of saving a scratch file when ucm was in `less` mode, which is admittedly confusing—I think the behavior is that after you `q` `less`, ucm will then render the output from loading the scratch file (potentially putting you back into `less`). To address that, my preference would be for ucm to drop out of `less` automatically when a scratch file is touched.

**Comment by aryairani** [comment] 2019-12-13 13:29
@anovstrup Yeah I think that was the actual motivation, and I should’ve done a better job of writing it up.

But should it kill any `less` or just a typechecking `less`?  Maybe any is okay.  It would be nice if there were some signal to have less finish its output before exiting, but maybe it doesn’t matter.

**Comment by anovstrup** [comment] 2019-12-13 17:59
@aryairani I guess my expectation is that if I save a scratch file, I'll see the resulting output in ucm right away regardless of whether another command's output was being displayed in less (assuming I've explicitly decided to save my scratch file; no aggressive auto-save doing it for me!). So I'd say the right path is to always kill less, but I agree that it would be best if we can have less dump the remaining output to the buffer first.

**Comment by anovstrup** [comment] 2019-12-13 18:01
@aryairani Question: is ucm actually spawning a `less` process? Or is it just emulating less with a library or something?

**Comment by aryairani** [comment] 2019-12-13 18:38
@anovstrup That seems like a reasonable expectation.

Yes, ucm is actually spawning a `less` process; I couldn't find a library that emulates it.  This happens in `Less.hs`.

I guess you'd somehow need to return a callback to kill `less`, and thread it back through the Output command (or a copy) — maybe Output returns a cancelOutput command, that you can call to interrupt a modal display? :-\

**Comment by anovstrup** [comment] 2019-12-16 02:01
@aryairani I spent some time on this over the weekend and can now appreciate the motivation for the simpler solution you proposed. 😛

I got stuck on a couple problems:

* **Dumping any output _not_ consumed by `less` into stdout when we kill `less`.** I tried to address this by giving the `createProcess` call the _read_ end of a pipe (using UseHandle instead of CreatePipe) created with `createPipe` and testing whether I can drain the pipe after `less` terminates (reading any unconsumed data from the _read_ end and writing it to stdout).  This solution almost works, except it doesn't behave correctly when `less` gets to the end of the input—`less` seems to be waiting for more input even though I close the _write_ end of the pipe before calling `waitForProcess`.  When the output is long enough that `less` does not consume all of it (and I don't scroll to the bottom), it works fine and the unconsumed output gets written to stdout after `less` exits. On short outputs, however, `less` just waits (it doesn't display the prompt message and doesn't quit early).

* **Killing a running `less` process when a scratch file is saved.** I was able to modify `Less.less` to return wait/kill callbacks, based on `System.Concurrent.Async.(async, wait, cancel)`.  I ran into trouble, though, when I tried to figure out how to make use of the kill callbacks in `Main.hs`/`HandleCommand.hs`/`HandleInput.hs`.  I think the real difficulty stems from the fact that each `Notify` command ends up spawning its own `less` process, and these are necessarily synchronous and blocking (if I'm not mistaken). As a result, the event loop isn't going to process other events or commands (the `UnisonFileChanged` event or a `CancelOutput` command) until _after_ the `less` process is terminated by the user.  

  The solution may be to handle the creation of the `less` processes up higher, so that all Notify commands encountered while handling a given input / watch-event end up piping output to a single shared `less` process in a non-blocking way. We'd kill the current `less` process (if any) any time a `UnisonFileChanged` event occurs and start a new one if there is no current `less` process when we handle a Notify command.

**Comment by anovstrup** [comment] 2019-12-17 21:53
@aryairani Update:

I've got some (very messy) work-in-progress checked in at https://github.com/anovstrup/unison/commit/3ccb299e92c8e3df7372f289ac40bf9b92379d68. 

On the first bullet point above, I determined that trying to dump output not consumed by `less` could only be "best effort", because (at least on my platform) `less` seems to do some lookahead (consuming more data from its input pipe than it actually displays). On the other hand, AFAICT, there's no signal that will cause less to write the remaining output and terminate.

I made progress on the second bullet, but I got stuck when it comes to actually killing the running `less` process.  The code to terminate the process currently does not run until the `less` process is terminated by the user, and I'm not really sure why. Do you think you could take a look at the commit?

**Comment by anovstrup** [comment] 2019-12-19 07:12
Update: 

As [noted on Slack](https://unisonlanguage.slack.com/archives/CLG4P0GSD/p1576710631043800?thread_ts=1576694725.041800&cid=CLG4P0GSD), I was able to figure out why file watcher was not enqueueing events until after `less` was terminated, even though they're on separate threads. Apparently, `System.Process.waitForProcess` blocks _all_ threads unless the program is compiled with the -threaded compiler flag. In our case, even using -threaded when compiling the unison executable does not fix it, perhaps because the call is made from the library code (and the compiler says that using -threaded only has an effect when compiling an executable). Using a spin-wait, however, resolved that issue:

```
spinWaitForProcess :: ProcessHandle -> IO ()
spinWaitForProcess pid = do
  c <- getProcessExitCode pid
  if isJust c then return () else do
    threadDelay 100000
    spinWaitForProcess pid
```

Unfortunately, I've hit another snag.  The `System.Process.terminateProcess` function does not actually terminate the `less` process—it seems to block instead.  When I replaced that call with a `Signal.Posix.Signals.signalProcess` call to try signals other than the default SIGTERM, I end up with a "permission denied (Operation not permitted)" error. I also get that error when I try to terminate the child `less` process manually from the command line, even though it should not be a privileged process. I suspect that the same error is responsible for `terminateProcess` not working. This may be a platform-specific issue, so it might be worthwhile for someone else to try running the code on a different platform.

**Comment by anovstrup** [comment] 2019-12-19 19:31
I updated [my wip commit](https://github.com/anovstrup/unison/commit/1e7173df998def4e2ff793bd23a6b51ce834a0c8). It would be helpful if someone could check this code out and see if they run into the same problem I do (`terminateProcess` failing to actually terminate the process) to determine whether the issue is platform-specific.

**Comment by anovstrup** [comment] 2019-12-19 23:43
More context on the problem: on my platform (Mac OS X), the `less` process that we fork from unison cannot be forcibly terminated either from within unison or externally (even with `sudo kill -9`!).  `ps` indicates that the process status is "?+".  The "+" indicates that "the process is in the foreground process group of its control terminal", according to the `ps` manual. The "?" is not documented in the man page, and I haven't been able to find an answer online. (I only found answers [like this one](https://www.unix.com/unix-for-dummies-questions-and-answers/31443-ps-command-returns.html) that explain the meaning of "?" in the TTY field of the `ps` output, not the state field.)

**Comment by anovstrup** [comment] 2020-01-21 20:37
@aryairani I think this issue can be closed.

**Closed** 2020-01-22 02:09 UTC
