### ISSUE TITLE
UCM should not report syntax errors below the fold

### ISSUE THREAD

**Issue by alvaroc1** [unisonweb/unison#4755] opened 2024-03-06 19:56 UTC
Version: release/0.5.17

```
x : Text 

---
a bunch of 
stuff that should
not affect parsing
...
```

```
queue/main> 

  Loading changes detected in ~/workspace-unison/scratch-dev/queue.u.


  offset=4:
  unexpected <outdent>
  expecting -> or newline or semicolon
    160 |
```

it reports a syntax error way deep below the fold

**Comment by aryairani** [comment] 2024-03-07 00:50
I have encountered this too

**Comment by ceedubs** [comment] 2024-03-07 01:56
Related: #3990

**Comment by sellout** [comment] 2024-07-09 06:59
Duplicate of #813.

**Closed as not planned by sellout** 2024-07-09 06:59 UTC
