### ISSUE TITLE
List.foldl defaults to Set.foldl when List.foldl is not available.

### ISSUE THREAD

**Issue by jordanemedlock** [unisonweb/unison#1682] opened 2020-09-20 23:07 UTC
Trying to use `List.foldl` type-checked as `Set.foldl` when I was trying to use it in a `sum` function.  

After trying to add this code to the codebase:

```
use .base

sum : [Nat] -> Nat
sum xs = List.foldl (+) 0 xs
```

I got the error message: 
```
  The 3rd argument to the function .base.Set.foldl is [.base.Nat], but I was expecting .base.Set a:
      6 | sum : [Nat] -> Nat
      7 | sum xs = List.foldl (+) 0 xs
  More specifically, I found .base.List where I was expecting .base.Set:
      6 | sum : [Nat] -> Nat
```

Which didn't make sense because I was explicitly namespacing `foldl` with `List`.  Going back, I realized that I had previously renamed `List.foldl` to `List.foldLeft`.  Fixing that fixed the issue.  However, I would expect that Unison would provide an error message saying `Can't find List.foldl` rather than, trying to use another a `foldl` function in a different namespace.

**Comment by pchiusano** [comment] 2020-09-21 13:38
Definitely a bug, thanks for reporting. Tentative guess is that this is falling back to TDNR which I believe (incorrectly) only looks at the last segment of the identifier. I don't think this is an issue with suffix-based resolution (but could be wrong).

**Comment by aryairani** [comment] 2020-09-21 13:51
I was able to reproduce the issue with this transcript:

    ```ucm                                                                          
    .> pull https://github.com/unisonweb/base:.releases._M1m .base                  
    .> move.term base.List.foldl base.List.foldLeft                                 
    ```                                                                             
    
    ```unison                                                                       
    use .base                                                                       
    sum : [Nat] -> Nat                                                              
    sum xs = List.foldl (+) 0 xs                                                    
    ```
```
  The 3rd argument to the function base.Set.foldl is [base.Nat], but I was expecting base.Set a:
  
      2 | sum : [Nat] -> Nat
      3 | sum xs = List.foldl (+) 0 xs
  
  More specifically, I found base.List where I was expecting base.Set:
  
      2 | sum : [Nat] -> Nat
```

**Comment by pchiusano** [comment] 2020-10-22 20:55
Closing as dupe of #845

**Closed as completed by pchiusano** 2020-10-22 20:55 UTC
Labels: tdnr, suffix-based-resolution
