### ISSUE TITLE
Unhelpful error message if doc backtick is unmatched

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#5353] opened 2024-09-17 19:21 UTC
If you have an unclosed backtick in a doc literal, the parser will continue searching for its match until the end of the file. As far as I know, using single backticks in markdown only supports inline code, so ideally this could give an error message citing the relevant line and noting that a backtick wasn't matched.

Here is an example:

```
{{
``foo t`` does stuff with `t.
}}
foo : Text -> Text
foo t = t ++ t
```

**What's the message you're seeing?**

```
  Loading changes detected in ~/code/unison/base.u.


  I got confused here:
  
   1678 | 
  
  resetting state
```

The error message isn't very helpful, and it continues past the fold in my scratch file and reports the error on line 1678.

**What would a better version look like?**

```
  Unmatched backtick in doc literal.
  
      2 | ``foo t`` does stuff with `t.
                                    ^
```

Environment (please complete the following information):

* `ucm --version` 0.5.26

**Comment by aryairani** [comment] 2024-09-18 14:59
Likely dupe of https://github.com/unisonweb/unison/issues/5073 (in progress)

**Comment by sellout** [comment] 2024-11-04 17:19
Yeah, duplicate of #5073.

**Closed as not planned by sellout** 2024-11-04 17:19 UTC
Labels: error-message, triaged
