### ISSUE TITLE
unison won't start if there's a broken symlink in the directory

### ISSUE THREAD

**Issue by seagreen** [unisonweb/unison#1021] opened 2019-12-04 23:23 UTC
```
$ mkdir test
$ cd test
$ unison -codebase . init
$ unison
<this works>
$ ln -s foo this-does-not-exist
$ unison

   _____     _
  |  |  |___|_|___ ___ ___
  |  |  |   | |_ -| . |   |
  |_____|_|_|_|___|___|_|_|

  Welcome to Unison!

  I'm currently watching for changes to .u files under ~/test

  Type help to get help. 😎

  Enter pull https://github.com/unisonweb/base .base to set up the default base library. 🏗

unison: this-does-not-exist: getModificationTime:getFileStatus: does not exist (No such file or directory)
```

@aryairani reports that this is a regression

EDIT: In case it wasn't clear, `unison` crashes after the last command

**Comment by int-index** [comment] 2019-12-12 12:31
I can't run `unison` in `$HOME` on macOS because of this:

```
ucm: Applications: getModificationTime:getFileStatus: does not exist (No such file or directory)
```

**Comment by aryairani** [comment] 2019-12-12 14:14
@int-index Is that also a broken symlink for you?

**Comment by int-index** [comment] 2019-12-12 14:15
Yes

**Comment by aryairani** [comment] 2019-12-12 14:23
We want to find a fix for this, but as a workaround, can you fix or delete the broken link?

**Comment by int-index** [comment] 2019-12-12 14:27
Sure, `rm Applications` did the trick.

**Comment by aryairani** [comment] 2019-12-12 14:29
I suspect it’s a bug in the file watching library we’re using, but haven’t had a chance to dig into it :/

**Comment by pete-ts** [comment] 2020-01-15 16:34
The bug only materializes if the current working directory being watched by unison contains a broken symlink, I have managed to reproduce it by adding a broken synlink in a directory, then running unison from inside it.

https://github.com/unisonweb/unison/blob/9f81ec91a9539f7baeb9a5810d2e843fe20ca214/parser-typechecker/src/Unison/Codebase/Watch.hs#L94

[listDirectory](https://hackage.haskell.org/package/directory-1.3.5.0/docs/System-Directory.html#v:listDirectory) claims that it will fail if a directory does not exist.

[getModificationTime](https://hackage.haskell.org/package/directory-1.3.5.0/docs/System-Directory.html#v:getModificationTime) also claims that it will fail if a directory does not exist.

What actually happens: `listDirectory` returns a broken symlink in the `[String]`, and does not seem to throw (at least on ubuntu 18.04), then when `getModificationTime` actually tries to get the modification time for the broken symlink, an exception is raised.

**Comment by pete-ts** [comment] 2020-01-15 18:39
@seagreen or @int-index would either of you have some time to build from source and check that this indeed fixes it for you? It seems to work on my current setup.

**Comment by pete-ts** [comment] 2020-01-17 16:06
Tested this on a mac too, working.

**Comment by aryairani** [comment] 2020-01-17 17:50
Great, thanks everyone.

**Closed by aryairani** 2020-01-17 17:50 UTC
Labels: bug
