### ISSUE TITLE
UCM crashes when adding nameless test

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#2520] opened 2021-10-19 19:13 UTC
```ucm
test> run (expect True)
```

After save:
```
    ⍟ These new definitions are ok to `add`:

    test.qubol1gu7o (Unison bug, unknown term)

  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.


    3 | test> run (expect true)

    ✅ Passed : Passed 1 tests. (cached)
```

```ucm
.> add

  ⍟ I've added these definitions:

  test.eoq0eoo9n2 (Unison bug, unknown term)


  I added some default metadata.

ucm: DatabaseIntegrityError (NoObjectForPrimaryHashId (HashId 25027))
CallStack (from HasCallStack):
  error, called at src/Unison/Codebase/SqliteCodebase.hs:928:29 in unison-parser-typechecker-0.0.0-8iNyHDVYveQ9Wi84mdnSZS:Unison.Codebase.SqliteCodebase
```

NOTE:
* If the term already has a name in the codebase; this won't crash.

**Comment by ChrisPenner** [comment] 2021-10-19 19:27
We should consider the UX here;
IMO, it's a bad idea™ to have unnamed (or randomly named) tests within a codebase; so we should likely NOT add the term and print a message saying how to give it a name?

**Comment by tapegram** [comment] 2021-11-07 18:00
I'd like to take a stab at this if no one else is working on it. Any suggestions on where in the code I should start off looking or any particular approaches? So far I have reproduced the failure in a transcript test, but otherwise I've just been scanning through the code trying to find if and where any first class handling of `test>` terms lives and if I'd be able to do a check for a name on `Add`.

**Comment by ChrisPenner** [comment] 2021-11-08 17:30
Additional context from slack:
![image](https://user-images.githubusercontent.com/6439644/140789897-a19929cc-ce09-413e-a16d-03b4014af784.png)

**Comment by aryairani** [comment] 2024-06-30 19:05
Closing this because ucm no longer crashes when adding the unnamed test:
<img width="306" alt="image" src="https://github.com/unisonweb/unison/assets/538571/29c9cd6f-c89f-4e31-9938-19ba65c15590">

**Closed as completed by aryairani** 2024-06-30 19:05 UTC
Labels: bug, codebase-manager / ucm
