### ISSUE TITLE
Unit value for delayed computation fails to parse

### ISSUE THREAD

**Issue by sharma7n** [unisonweb/unison#1108] opened 2019-12-31 15:16 UTC
Steps:

1. `ucm init` into a clean codebase.

2. Add the following definition to `scratch.u`:

```
app : '{IO} ()
app = let'
  io.printLine "Hello, world!"
```

3. `ucm` > `add`

4. Remove the text from `scratch.u`.

5. `ucm` > `edit app`

6. The text is regenerated in `scratch.u` as:

```
app : '{IO} ()
app () = printLine "Hello, world!"
```

7. Add a trivial watch expression like `> 5` to `scratch.u`.

Result:

`ucm` will complain:

```
  /home/ubuntu/environment/scratch.u:2:5:
  unexpected (
      2 | app () = printLine "Hello, world!"
```

Expected:

Code that unison writes/edits for me always parses correctly.

**Comment by sharma7n** [comment] 2019-12-31 15:17
Sorry if this is a duplicate! I tried searching on "unexpected (" in the backlog and there were too many issues to sort through and none of them seemed relevant at a glance.

**Comment by aryairani** [comment] 2019-12-31 18:12
Hi @sharma7n, sorry about this.  

It is a known issue (#642), but it's impossible to find with search because [github ignores `(` `)` in searches](https://help.github.com/en/github/searching-for-information-on-github/searching-code#considerations-for-code-search).  But it's supposed to be fixed already.

Can you check the output of `ucm --version`?

**Comment by sharma7n** [comment] 2019-12-31 18:35
No problem! Thanks for finding the duplicate.

`ucm --version` returns: "ucm version: release/M1g". I'm running on a fresh Ubuntu 18.04 workspace and just installed unison via homebrew this morning, if that helps.

**Comment by aryairani** [comment] 2019-12-31 23:57
I was thrown off by the `let'` in your example (should be `'let`, but I didn't notice it).

But with that out of the way, I confirmed that this is fixed in `master`, but not in a binary release yet unfortunately.  Are you comfortable with building from source?

**Closed** 2020-01-01 00:16 UTC

**Comment by sharma7n** [comment] 2020-01-01 00:23
Ah my bad, that should have definitely been `'let`. Sounds good - I'll try building this from source and let you know if it's still an issue.
