### ISSUE TITLE
performance of ucm commands

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#631] opened 2019-08-03 09:38 UTC
`ls foldl` takes a bit over 1 second to return a result, for me.  Laggy interaction makes the tool feel a lot less fluid and direct.  It would be great if it could seem 'instantaneous'.

Caveat: I'm on Ubuntu (18.04.2), on top of virtualbox (using a VDI storage volume) on top of Windows 10.  M1a.  

Commands like `help` return instantly.

**Comment by pchiusano** [comment] 2019-08-03 10:23
I have noticed some slowness also (for view command too) and I see no reason why it shouldn’t be instantaneous. Would like to get to the bottom of it! A couple data points:

If you tab complete after find foldl, tab completions show up instantly for me. This suggests slowness is not in searching the namespace but is something about preparing and rendering those results for display. A few ideas:

Could be that it has to pull type signature from the codebase and hit the disk for all the results. If this were it, adding some caching might do the trick. 

Could be the actual process of producing the pretty doc for rendering, like if TypePrinter itself were really slow. Doesn’t seem super likely, that should just be a linear pass over the type AST which will be fast.

Could be the actually prettyprinting rendering. Doesn’t seem likely as other much larger pretty docs render quickly.

The tab completion code path isn’t exactly the same as the code to show the results, so wondering if there’s something weird in that step of converting the string to a set of results, before those results are prepared for display.

**Comment by pchiusano** [comment] 2019-08-03 18:13
Ran a couple experiments and am narrowing this down some. Loading the type from disk is fast, 1e-4 seconds for me, so you could load 1000 search results in 100ms, and `find foldl` only returns 1 result. I also tried getting rid of the type pretty printing and just print out the name of the definition... still pretty slow, like half a second. So that likely rules out the type printer.

**Comment by zenhack** [comment] 2019-08-10 23:25
This is affecting me as well (See also #700). Codebase is posted here: https://github.com/zenhack/unison-parsers

...but it sounds like you're able to reproduce anyway.

**Comment by pchiusano** [comment] 2019-09-04 16:22
I suspect issue is same as discussed here: https://unisonlanguage.slack.com/archives/CLG4P0GSD/p1567609298074200 basically pointing to preparing the pretty-printing environment, which is needlessly searching through the full history, which seems like it has a simple fix. That would be consistent with tab completion (which doesn't require that) is fast.

> I also tried getting rid of the type pretty printing and just print out the name of the definition... still pretty slow, like half a second. So that likely rules out the type printer.

I don't recall how I did this exactly, but if I just used `show` instead of the pretty printer, we'd still be paying for the cost of building that pretty printing environment, so this is also consistent with a needless full causal history search being the root cause.

Looking forward to closing this one out!

**Comment by aryairani** [comment] 2019-09-05 21:34
@atacratic I am working on this group of bugs.  I don't think I've done anything that would fix `ls foldl`, but I can't reproduce.  Can you?

**Comment by atacratic** [comment] 2019-09-07 08:34
@aryairani yup, it reproduces for me on M1c using the attached .unison directory.  (Note I think the directory was produced by M1a.)  Just type `ls foldl`.
[z.unison.zip](https://github.com/unisonweb/unison/files/3586408/z.unison.zip)

**Comment by aryairani** [comment] 2019-09-07 13:10
Thanks, I will try; though would you check whether it still occurs on `master`? (vs `m1c`)

**Comment by atacratic** [comment] 2019-09-07 13:25
Yup - still repros on master as of now (master@d05c459e2).

**Comment by aryairani** [comment] 2019-09-07 18:49
Haha, ok.  I definitely was able to reproduce with z.unison.zip.  Will keep you posted.

**Comment by aryairani** [comment] 2019-09-07 18:55
@atacratic Not a lot to go on yet, but using the `topic/trace-findInHistory` branch, I can see that doing an `ls foldl` for you is searching for `##Sequence` which (oops) no longer exists.

**Comment by aryairani** [comment] 2019-09-07 19:07
Sorry, was a little confused.  I guess `##Sequence` is the official name for `[]`, but your codebase still uses the name `##List` which had showed up in a couple of the builds by accident.  This worked for me, to fix the `ls` slowness:

```
.> pull https://github.com/unisonweb/unisonbase.git
.> delete.type base.List##List
```

**Comment by atacratic** [comment] 2019-09-07 19:11
Ok cool, nice one! Just a transient thing to not worry about then?

**Comment by aryairani** [comment] 2019-09-07 19:13
In that particular case, yes.  So I'm gonna close this ticket, and we'll track any remaining slow commands in new, separate tickets.  :)   I created the `topic/trace-findInHistory` branch to help diagnose them, and will try to keep it up to date, in the absence of a comprehensive command-line flags system.

**Closed** 2019-09-07 19:13 UTC
