### ISSUE TITLE
edit+slurp round-trip fails for a function that starts with a delay

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#642] opened 2019-08-03 21:51 UTC
I input
```
ability GetTime where
  systemTime : .base.io.EpochTime
             
test : '{GetTime} base.io.EpochTime
test = 'GetTime.systemTime
```
I add this and do `edit test`, and get back
```
  test : '{GetTime} base.io.EpochTime
  test () = GetTime.systemTime
```
But this then doesn't parse:
```
  /home/chris/u1/scratch.u:5:8:
  unexpected (
      5 |   test () = GetTime.systemTime
```

In a world of pattern matching definitions at the top level, it would parse - but for now this is a pretty-printer bug - it should output `test _ = GetTime.systemTime` instead of `test () = GetTime.systemTime`.

Note that a function which is defined 'longhand' instead of using the delay sugar is pretty-printed fine.  

(M1a)

**Comment by pchiusano** [comment] 2019-08-12 16:33
Note: Synthetic var names should be valid identifiers.

**Comment by pchiusano** [comment] 2019-08-12 16:35
But this issue might be fixed with just some changes to pretty-printer - any lambda which takes `()` as as argument is show quoted.

**Comment by runarorama** [comment] 2019-11-27 20:05
Looking into this a bit. It's unfortunate that we're actually parsing `'foo` as a lambda with a variable named `()`, since `()` isn't a valid name at all. But changing that would invalidate existing codebases.

**Closed** 2019-11-28 03:52 UTC
Labels: help wanted, pretty-printer

**Comment by aryairani** [comment] 2019-11-28 15:17
@runarorama That is unfortunate... I didn’t follow what you meant about changing it; how will it break existing codebases (or what’s the fix?)

**Comment by runarorama** [comment] 2019-11-28 16:24
Right now we process the `'` syntax as a lambda with a variable named `()`, so existing codebases will be rife with these. It’s a horrible hack and we should change it in the next iteration of codebase representation.

**Comment by aryairani** [comment] 2019-11-28 18:42
What kind of change does it need?

If the issue is 

a) the illegal names, could we:

a1)
* stop creating new variables with illegal names immediately
* clean up existing names during a codebase update

or a2) solve it by supporting a name-escaping syntax, so no names are illegal?

Or b) should it have a new representation without synthetic names?
