### ISSUE TITLE
What's the best way to present results of an `add` / `update`?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#414] opened 2019-03-23 20:58 UTC
![image](https://user-images.githubusercontent.com/538571/54871585-d96bed80-4d8c-11e9-9c20-e7a76e5405c4.png)

**Comment by pchiusano** [comment] 2019-04-08 20:49
On `add`, there's all these different cases for a definition that was in the file. It can be _new_, a duplicate of something already in the codebase, new but with the same name as something already in the branch, in which case it's treated as an update, and some edge cases like _new definition with the same name as a data type constructor_, _new data type constructor with the same name as an existing term_.

Right now we put each of these cases in its own "section" as show above, but maybe there's some nicer way of presenting this information?  

Rúnar: Maybe add a `why` / `verbose` command to explain the (eventually) numbered `add`/`update` results.

**Closed** 2019-06-25 21:10 UTC
Labels: codebase-editor, design needed, help wanted
