### ISSUE TITLE
Doc parsing: parentheses throw off definition references

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4993] opened 2024-05-21 13:41 UTC
Consider the following doc:

```
{{
This is parsed correctly: ( {List.map} )
This is not: ({List.map})
}}
```

Here is the result. Notice that the first parses as a `Link` but the second does not.

```
          Paragraph
            [ Word "This"
            , Word "is"
            , Word "parsed"
            , Word "correctly:"
            , Word "("
            , Special (SpecialForm.Link (Right (Term.Term (Any (do List.map)))))
            , Word ")"
            , Word "This"
            , Word "is"
            , Word "not:"
            , Word "({List.map})"
            ]
```

**Comment by ceedubs** [comment] 2024-06-30 20:02
I think that this might be a duplicate of #2483 , though the use of "bracket" in that title confuses me.

**Comment by sellout** [comment] 2024-07-09 06:57
Duplicate of #2483.

**Closed as not planned by sellout** 2024-07-09 06:57 UTC
Labels: help wanted, parser
