### ISSUE TITLE
`update` command is slow and provides no feedback

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2339] opened 2021-08-19 16:13 UTC
`update` sometimes take a long time. It seems like it might be related to patch size, but not sure. It would be nice for starters to just report more output. My guess is that both the initial `add` is slow  #2338 and then propagation is also slow, possibly for unrelated reasons.

Like during propagation, some sort of progress or logging messages might be good.

**Comment by aryairani** [comment] 2021-09-30 15:59
@pchiusano Can you suggest some library we could try an `update` on to reproduce this?

**Comment by aryairani** [comment] 2023-12-06 21:07
Closing this because it refers to the old update process.

**Closed as completed by aryairani** 2023-12-06 21:07 UTC
Labels: performance, P1, E16, R2, I3, C2
