### ISSUE TITLE
Roundtrip error in `metadata.licenseTypes.bsd2.doc`

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#4728] opened 2024-02-28 16:42 UTC
```
metadata.licenseTypes.bsd2.doc : Doc
metadata.licenseTypes.bsd2.doc =
  {{
  The [BSD 2-Clause](https://opensource.org/licenses/BSD-2-Clause) license.
  
  # License text
  
    {{ (LicenseType d) = bsd2 d }}
  }}
```

Should be like: 

```
metadata.licenseTypes.bsd2.doc : Doc
metadata.licenseTypes.bsd2.doc =
  {{
  The [BSD 2-Clause](https://opensource.org/licenses/BSD-2-Clause) license.
  
  # License text
  
    {{ let 
          (LicenseType d) = bsd2
          d
    }}
  }}
```

**Comment by sellout** [comment] 2024-07-09 06:52
Duplicate of #2889.

**Closed as not planned by sellout** 2024-07-09 06:52 UTC
Labels: round-trip

**Comment by sellout** [comment] 2024-07-09 06:56
Sorry, shouldn’t have closed as “completed”.
