### ISSUE TITLE
pretty printer crash: reference to unknown combinator when printing a function

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3974] opened 2023-05-10 01:33 UTC
**This issue description is the result of a transcript. The raw input transcript can be viewed [here](https://gist.github.com/ceedubs/77b29537899c8a5c56bc7968400d815d).**

# Transcript output

This transcript shows an example of a function that returns the expected result but causes the pretty-printer to fail with the error `reference to unknown combinator: #0lib3`

```ucm
.> builtins.merge

  Done.

```
There is probably a way to reproduce this issue with less code, but I ran into it while writing some recursion scheme code which I have simplified a bit for this transcript:

```unison
structural type Functor f = Functor (∀ g r1 r2. (r1 -> {g} r2) -> f r1 -> {g} f r2)

Functor.map : Functor f -> (∀ g r1 r2. (r1 -> {g} r2) -> f r1 -> {g} f r2)
Functor.map = cases Functor f -> f

structural type ListF a r = Nil | Cons a r

ListF.functor : Functor (ListF a)
ListF.functor = Functor (f -> cases
  Nil -> Nil
  Cons h t -> Cons h (f t))

hylo : Functor f -> (f b -> {h1} b) -> (a -> {h2} f a) -> a -> {h1, h2} b
hylo f fold unfold =
  go start = fold ((Functor.map f) go (unfold start))
  go

addNats : ListF Nat Nat -> Nat
addNats = cases
  Cons x y -> x + y
  Nil -> 0

unfoldNats : Nat -> ListF Nat Nat
unfoldNats n = if n <= 4 then Cons n (Nat.increment n) else Nil
```

Running this code will sum 0-4, which returns 10 as expected.

```unison
> hylo ListF.functor addNats unfoldNats 0
```

```ucm

  ✅
  
  scratch.u changed.
  
  Now evaluating any watch expressions (lines starting with
  `>`)... Ctrl+C cancels.

    1 | > hylo ListF.functor addNats unfoldNats 0
          ⧩
          10

```
But if we partially apply the code to get back a `Nat` -> `Nat`, then we get a runtime error with an unhelpful error message. I believe that this is coming from the pretty-printer when attempting to pretty-print the function.

```unison
> let
  x : Nat -> Nat
  x = hylo ListF.functor addNats unfoldNats
  x
```

```ucm

  ✅
  
  scratch.u changed.
  
  Now evaluating any watch expressions (lines starting with
  `>`)... Ctrl+C cancels.

  reference to unknown combinator: #0lib3

```

🛑

The transcript failed due to an error in the stanza above. The error is:

  reference to unknown combinator: #0lib3

**Comment by aryairani** [comment] 2024-05-02 15:14
This seems to be fixed as of 0.5.19:

# Transcript Output

This transcript shows an example of a function that returns the expected result but causes the pretty-printer to fail with the error `reference to unknown combinator: #0lib3`

```ucm
.> builtins.merge

  Done.

```
There is probably a way to reproduce this issue with less code, but I ran into it while writing some recursion scheme code which I have simplified a bit for this transcript:

```unison
structural type Functor f = Functor (∀ g r1 r2. (r1 -> {g} r2) -> f r1 -> {g} f r2)

Functor.map : Functor f -> (∀ g r1 r2. (r1 -> {g} r2) -> f r1 -> {g} f r2)
Functor.map = cases Functor f -> f

structural type ListF a r = Nil | Cons a r

ListF.functor : Functor (ListF a)
ListF.functor = Functor (f -> cases
  Nil -> Nil
  Cons h t -> Cons h (f t))

hylo : Functor f -> (f b -> {h1} b) -> (a -> {h2} f a) -> a -> {h1, h2} b
hylo f fold unfold =
  go start = fold ((Functor.map f) go (unfold start))
  go

addNats : ListF Nat Nat -> Nat
addNats = cases
  Cons x y -> x + y
  Nil -> 0

unfoldNats : Nat -> ListF Nat Nat
unfoldNats n = if n <= 4 then Cons n (Nat.increment n) else Nil
```

Running this code will sum 0-4, which returns 10 as expected.

```unison
> hylo ListF.functor addNats unfoldNats 0
```

```ucm

  Loading changes detected in scratch.u.

  ✅
  
  scratch.u changed.
  
  Now evaluating any watch expressions (lines starting with
  `>`)... Ctrl+C cancels.

    1 | > hylo ListF.functor addNats unfoldNats 0
          ⧩
          10

```
But if we partially apply the code to get back a `Nat` -> `Nat`, then we get a runtime error with an unhelpful error message. I believe that this is coming from the pretty-printer when attempting to pretty-print the function.

```unison
> let
  x : Nat -> Nat
  x = hylo ListF.functor addNats unfoldNats
  x
```

```ucm

  Loading changes detected in scratch.u.

  ✅
  
  scratch.u changed.
  
  Now evaluating any watch expressions (lines starting with
  `>`)... Ctrl+C cancels.

    2 |   x : Nat -> Nat
          ⧩
          start ->
            (cases
              ListF.Cons x y -> x Nat.+ y
              Nil            -> 0)
              (map
                (Functor
                  (f ssloeiad4p1 -> (match ssloeiad4p1 with
                    Nil            -> Nil
                    ListF.Cons h t -> ListF.Cons h (f t))))
                (#9vao7a4d3c
                  (Functor
                    (f ssloeiad4p1 -> (match ssloeiad4p1 with
                      Nil            -> Nil
                      ListF.Cons h t -> ListF.Cons h (f t))))
                  (cases
                    ListF.Cons x y -> x Nat.+ y
                    Nil            -> 0)
                  (n ->
                    (if n <= 4 then
                      ListF.Cons n (Nat.increment n)
                    else Nil)))
                ((n ->
                  (if n <= 4 then ListF.Cons n (Nat.increment n)
                  else Nil))
                  start))

```

**Closed as completed by aryairani** 2024-05-02 15:14 UTC
Labels: pretty-printer, crash
