### ISSUE TITLE
when trying to pull: "unison: user error trying to copy the definition of #cf8c1"

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1505] opened 2020-05-01 22:35 UTC
[the raw version of this issue description is a valid unison transcript demonstrating the problem]

Net effect is some unison code I pushed a while ago can't be retrieved.  There have probably been a bunch of fixes to the push/pull mechanism since then I guess.  I still have the code in one of my local codebases so no biggie.  

```ucm
.> pull https://github.com/unisonweb/base:.trunk .base
.> pull https://github.com/atacratic/unison-datetime.git _unison_datetime
```
crashes ucm with the following message during the second pull...

```
unison: user error (😞 I was trying to copy the definition of #cf8c1, but I couldn't find it as a type _or_ a term.)
```

when I restart and check that hash I see...

```
.> names #cf8c1

  Term
  Hash:   #cf8c1a0tu8
  Names:  _base.releases._M1j.test.internals.v1.Test.run
          _base.releases._M1j.test.run
          _base.releases._M1k.test.internals.v1.Test.run
          _base.releases._M1k.test.run
          _base.releases._M1l.test.internals.v1.Test.run
          _base.releases._M1l.test.run
          _base.releases._latest.test.internals.v1.Test.run
          _base.releases._latest.test.run
          _base.trunk.test.internals.v1.Test.run
          _base.trunk.test.run
          base.test.internals.v1.Test.run
          base.test.run

```

Is https://github.com/atacratic/unison-datetime.git broken?

**Comment by aryairani** [comment] 2020-05-01 23:33
@atacratic Sorry, but yes, it is likely broken; and if it is, then pushing again without deleting and recreating that repo empty first won't help.  (Corollary, pushing again after deleting and recreating that repo empty first will help.) :)

There are a couple things we could do in a later release to help, but as of this writing, recreating the github repo is your best bet.  😞

**Comment by aryairani** [comment] 2020-05-01 23:38
Possible duplicate of #1502, although it's interesting that the error message isn't the same.

**Comment by atacratic** [comment] 2020-05-03 23:20
Have recreated the repo, so this is OK now from my point of view.  Feel free to close it if it's just a historical problem.

**Comment by etorreborre** [comment] 2020-05-07 09:13
I have a similar issue when trying to pull `unisonhttp`:
```
.> pull https://github.com/Nipsuli/unisonhttp 
ucm: user error (😞 I was trying to copy the definition of #5islt, but I couldn't find it as a type _or_ a term.)
```

**Comment by aryairani** [comment] 2020-05-12 21:20
@etorreborre If you're still seeing this, we'll have to ask @nipsuli to recreate his repo unfortunately :-\

**Closed by aryairani** 2020-05-12 21:20 UTC
