### ISSUE TITLE
Single backtick syntax for monospace does not render inside parenthesis

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#4777] opened 2024-03-11 20:33 UTC
When the first word inside a parenthetical statement is monospaced with the single backtick syntax: 

```
test = {{

  `hi` hi

  (this is a parenthesis `hi` blah)

  (`now` it starts with a backtick, which is not treated as monospace)
}}
```

The local, share, and website UI does not render the monospace syntax as monospace. 

![Screenshot 2024-03-
[backticksInParens.md](https://github.com/unisonweb/unison/files/14564295/backticksInParens.md)
11 at 1 29 54 PM](https://github.com/unisonweb/unison/assets/7613551/083814c9-3a89-4f3a-965d-88aa9b7e56fc)

A transcript is attached, but you will need to open the UI to see the issue. 
[backticksInParens.md](https://github.com/unisonweb/unison/files/14564303/backticksInParens.md)

**Comment by pchiusano** [comment] 2024-03-11 20:39
Yeah looks like a parser issue

```
    2 | > {{ (`hello` there ) }}
          ⧩
          Paragraph [Word "(`hello`", Word "there", Word ")"]
```

Notice it's just parsing the opening paren and the subsequent backticked word as a single token.

**Comment by pchiusano** [comment] 2024-03-11 20:51
This part of Lexer.hs seems like the culprit. It gobbles up a word until reaching a non-space character, but it should probably stop if encountering a backtick or double quote.

<img width="936" alt="CleanShot 2024-03-11 at 15 50 44@2x" src="https://github.com/unisonweb/unison/assets/11074/540a78bb-9f50-449c-a97a-e2afa9db48ef">

**Comment by sellout** [comment] 2024-07-04 16:58
I think this is the same issue as #4633.

`wordy` needs to `lookAhead` for any potential `leafy` opening sequences (here it says `docOpen`, but that is just coincidentally the same symbol as the opening for transcludes, but really, a single `{` suffices, as well as backtick, `''`, `*`, `~`, `@source`, etc.). It might need to `P.try leafy` character by character, as a `[` is only the end of `wordy` if there are later `](` and `)`, for example.

**Comment by sellout** [comment] 2024-07-09 06:57
Duplicate of #2483.

**Closed as not planned by sellout** 2024-07-09 06:57 UTC
Labels: {{docs}}
