### ISSUE TITLE
Can't construct type that "holds" a function that references an ability by variable on both the input and output

### ISSUE THREAD

**Issue by alvaroc1** [unisonweb/unison#4135] opened 2023-06-26 18:10 UTC
Using development version: 39b76f3

```unison
unique type Holder g
  = Holder ('{g} () ->{g} ())

main = do
  fn : '{IO} () ->{IO} ()
  fn effect = !effect

  v : Holder IO
  v = Holder fn
  ()
```

```ucm
  The expression in red
  
                needs the abilities: {IO}
    but was assumed to only require: {}
  
  This is likely a result of using an un-annotated function as an argument with concrete abilities. Try adding an annotation to the function definition whose body is red.
  
     10 |   v = Holder fn
```

This is possibly a simpler version of the following issue: 
https://github.com/unisonweb/unison/issues/4134

**Comment by SystemFw** [comment] 2023-06-26 18:29
I think this is a duplicate of https://github.com/unisonweb/unison/issues/4084

**Comment by pchiusano** [comment] 2023-06-27 16:02
Yes, this is the same issue as #4084 (we actually simplified an example very similar to yours to the one in #4804). Going to close this one.

**Closed as completed by pchiusano** 2023-06-27 16:02 UTC
