### ISSUE TITLE
SqliteQueryException in UCM when running 'update' with only watch expressions in scratch.u

### ISSUE THREAD

**Issue by typerlc** [unisonweb/unison#4438] opened 2023-11-29 02:47 UTC
The following exception is generated when running `update` after loading a .u file with only watch expressions.

The attached transcript reproduces the issue.

[update-exception-transcript.md](https://github.com/unisonweb/unison/files/13495559/update-exception-transcript.md)

Output is:

```
SqliteQueryException {sql = "SELECT object.id FROM object JOIN hash ON object.primary_hash_id = hash.id WHERE hash.base32 = ? COLLATE NOCASE", params = [SQLText "dfs8orl88dbd401n1jhqttsltaqdtfiuddb16u3vtclhlljg2eslt7q7b1af5lmk0ef8geo2hqn7ng8buadh5ekncllpes044phd19g"], exception = ExpectedExactlyOneRowException {rows = "[]"}, callStack = [], connection = Connection { name = "main", file = "/Users/richardc/.unison/v2/unison.sqlite3" }, threadId = ThreadId 884}
```

Unison installed via brew on MacOS 12.7.1:
```
❯ ucm version
ucm version: release/M5i (built on 2023-11-28)

❯ uname -a
Darwin Christines-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Oct  4 23:55:28 PDT 2023; root:xnu-8020.240.18.704.15~1/RELEASE_X86_64 x86_64

❯ sw_vers
ProductName:	macOS
ProductVersion:	12.7.1
BuildVersion:	21G920
```

**Comment by aryairani** [comment] 2023-11-29 15:01
Possible duplicate of #3376, #3475, #4375, #3288

**Comment by aryairani** [comment] 2023-11-29 17:54
`add` also crashes in this case.

**Closed as completed** 2023-11-30 22:27 UTC
