### ISSUE TITLE
Typechecking fails silently when a pattern binding clashes with an ability operation name

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1625] opened 2020-06-22 21:14 UTC
Transcript to reproduce:

```
    First we'll need an ability operation to have a name clash with.

    ```unison
    ability A where
      a : ()
    ```

    ```ucm
    .> add
    ```

    The following definition is accepted fine.

    ```unison
    p _ =
      q _ = ()
      match !q with
        b -> ()

    ```

    ```ucm
    .> add
    ```

    This definition is rejected with no error message.  The only change is b has become a in the pattern match.
     - I think it should be accepted despite reusing the name a in a pattern binding
     - and it shouldn't fail with no error.

    ```unison:error
    p' _ =
      q _ = ()
      match !q with
        a -> ()

    ```
```

The final stanza produces no output, so in a live session it looks like this:
```
.>
.>
```

Transcript output attached: [pattern-clash.output.md.txt](https://github.com/unisonweb/unison/files/4815600/pattern-clash.output.md.txt)

Probably the same underlying issue as #1175 

(trunk@dafb3c)

**Comment by aryairani** [comment] 2020-06-22 21:35
Nice work, thanks for this.

**Comment by pchiusano** [comment] 2020-11-11 17:20
This is almost certainly a dupe of #1731

**Comment by pchiusano** [comment] 2020-11-30 18:00
@dolio is going to make sure this has been fixed

**Comment by dolio** [comment] 2020-11-30 21:11
This is now fixed via fixing a duplicate bug.

**Closed as completed by dolio** 2020-11-30 21:11 UTC
Labels: typechecker
