### ISSUE TITLE
transcripts give cryptic error when encountering ``` in valid unison code

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2863] opened 2022-02-07 01:13 UTC
Transcript:
````
```unison
-- ignore this line, it's a comment ```
foo123 = "great"
```
````

Result:
```
  ❓
  
    A parsing error occurred while reading a file:
  
    TrivialError (SourcePos {sourceName = "foo.md", sourceLine = Pos 5, sourceColumn = Pos 1} :| []) (Just EndOfInput) (fromList [Label ('"' :| "ucm\""),Label ('"' :| "unison\""),Label ('s' :| "paces")])
```

Adding an extra backtick, per markdown, doesn't help, though the error message is different:
`````
````unison
-- ignore this line, it's a comment ```
foo123 = "great"
````
`````

```
  ❓
  
    A parsing error occurred while reading a file:
  
    TrivialError (SourcePos {sourceName = "foo.md", sourceLine = Pos 5, sourceColumn = Pos 1} :| []) (Just EndOfInput) (fromList [Label ('"' :| "```\""),Label ('u' :| "nfenced")])
```

Possibly related to #2826. Do we just need to support backtick counting and thicker fences?

**Comment by aryairani** [comment] 2022-02-09 20:13
At the very least, the error message isn't helpful, and even if we say ```` ``` ```` has a higher priority than `--`, we should support thicker fences to allow this.

**Comment by sellout** [comment] 2024-07-09 06:54
Duplicate of #2826.

**Closed as not planned by sellout** 2024-07-09 06:54 UTC
Labels: transcripts
