### ISSUE TITLE
support some kind of comment syntax in the transcript parser

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4420] opened 2023-11-22 17:31 UTC
Editors want to use `<!-- -->` for `.md` docs; so maybe that, or wasn't there a `#` syntax that worked in some cases?

**Comment by pchiusano** [comment] 2023-11-27 18:54
You can always just remove the `ucm` and `unison` from backticked blocks. Not as convenient if you're wanting to comment out multiple sections I guess.

**Comment by aryairani** [comment] 2023-11-28 15:06
I think we can also already use `--` inside of `ucm` blocks

**Comment by sellout** [comment] 2024-10-01 16:49
Whoops, #5141 was a duplicate of this, and it’s fixed by the switch to CMark in #5204.

**Closed as completed by sellout** 2024-10-01 16:49 UTC
Labels: transcripts
