### ISSUE TITLE
Issue rendering term on local share

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#4112] opened 2023-06-20 15:06 UTC
![image](https://github.com/unisonweb/unison/assets/6439644/2b8adbb7-aa8d-4919-a385-09836b507e6a)

**Comment by pchiusano** [comment] 2023-06-20 16:43
I just tried on trunk (after calling `./dev-ui-install.sh`), and things seem to be working fine. Haven't tried the latest M4i release.

<img width="1063" alt="image" src="https://github.com/unisonweb/unison/assets/11074/ff666194-f53a-48fb-9ec4-51fdbd030481">

Do we have more details on this? (Like what version it was using?)

**Comment by ChrisPenner** [comment] 2023-06-21 00:42
The slack chat said it was a brew install giving them issues https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1687076932249129

**Comment by hojberg** [comment] 2023-12-22 15:56
Closing since we haven't been able to reproduce

**Closed as completed by hojberg** 2023-12-22 15:56 UTC
