### ISSUE TITLE
failure to upgrade "I couldn't find 1 constructor(s)"

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#4491] opened 2023-12-08 17:28 UTC
When I try to upgrade any of the dependencies of [my metrics library](https://share.unison-lang.org/@stew/metrics) I get the error:

```
metrics/oldmain> upgrade base base_2_9_1                        

  I couldn't complete the update because I couldn't find 1 constructor(s) for
  Synchronous.Syncrounous where I expected to. I found: []
  
  You can use `view Synchronous.Syncrounous` and
  `alias.term <hash> Synchronous.Syncrounous.<ConstructorName>` to give names to each constructor,
  and then try again.
```

**Comment by aryairani** [comment] 2023-12-08 17:42
@stew What do you get when you view the type? (We can screenshare if you want)

@mitchellwrosen  is currently working on some pre-condition checks for `upgrade` that will give more detail about what would go wrong and why and how to fix it.

Probably this can be fixed by creating the missing constructors.

**Comment by stew** [comment] 2023-12-08 19:19
https://share.unison-lang.org/@stew/metrics/code/releases/1.0.0/latest/types/synchronous/Synchronous

**Comment by stew** [comment] 2023-12-08 19:19
the constructor isn't missing

**Comment by mitchellwrosen** [comment] 2023-12-08 21:11
@stew I tried cloning `metrics` just to reproduce; is there a branch on which I can try the command and see the error?

> upgrade base base_2_9_1

**Comment by hojberg** [comment] 2023-12-08 21:18
Could the subtle spelling mismatch `Synchronous.Syncrounous` be the cause?

**Comment by aryairani** [comment] 2023-12-09 17:53
@stew Wait, so did we resolve this yesterday?

**Comment by pchiusano** [comment] 2023-12-11 17:12
Summarizing the conclusion from this: the data type had an unnamed constructor. The upgrade process currently requires that constructors have names in order to `upgrade` a type, since it converts 1 same-named constructor to another.

I feel like an ideal experience in this situation would be:

* Do the upgrade, since it's a type with just one constructor, so there's no ambiguity about what should be mapped to what.
* Also do the upgrade if the hashes are the same in both cases.
* Warn the user "I upgraded `Foo`, but its constructor is missing a name. You can give it a name using `<instructions>`."

But I also feel like this is a somewhat rare case, and it will get more rare with the new `move` command that @tstat implemented.

I think the current message is reasonable but could maybe be worded a little more clearly and without weird notation. Maybe:

> I couldn't complete the upgrade because one of your data types, `Synchronous` has unnamed constructors. `upgrade` relies on all types having named constructors to map constructors of each type to their upgraded versions.
> 
> You can fix this up via `<instructions>`
> ... then try the `upgrade` again.

**Comment by aryairani** [comment] 2023-12-13 15:04
Agree about ideal experience, but with the current text-based system, we need an actual name to print, not just a mapping from `#0` to `#0`. A message wording update is in #4503

**Closed as completed** 2023-12-13 15:11 UTC
