### ISSUE TITLE
Pretty Printer: missing parens in sub expression pattern match.

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2337] opened 2021-08-19 00:27 UTC
pattern matching like so:

```hs
myFunction arg =
  (MyType someValue) = arg
  -- ...
```

compiles and works great, but is pretty printed like so:

```hs
myFunction arg =
  MyType someValue = arg
  -- ...
```

which does not compile.

**Comment by dolio** [comment] 2021-08-19 14:50
I think it should just not be necessary to put the match in parentheses. Maybe there's some ambiguity that makes that difficult, though.

**Comment by pchiusano** [comment] 2021-08-19 15:46
The issue is that

```
MyType someValue = arg
```

Can be interpreted as defining a function `MyType`, which has one argument `someValue`.

The fix might be to have the pretty-printer use `<-` for destructuring bind. The parser could still admit both options. Or maybe just add parens in this situation - you don't always need parens though, like for `(x,y) = blah` that is unambiguously a destructuring bind.

I think this is a dupe of another issue that @atacratic reported, but can't find it at the moment.

#1898

**Comment by atacratic** [comment] 2021-08-19 17:58
Dup of #1774, more discussion along the same lines in #1772.

edit: added a thought [here](https://github.com/unisonweb/unison/issues/1772#issuecomment-902129435)

**Comment by runarorama** [comment] 2021-09-09 00:49
The example as presented here doesn't exhibit this issue.

```
unique type Foo = Foo Text

fn arg = 
  (Foo "hi") = arg
  bug 0
```

Pretty-prints back as:

```
fn : Foo -> Nat
fn = cases Foo "hi" -> bug 0
```

@hojberg do you have a failing example?

**Closed as completed** 2021-09-09 03:14 UTC
Labels: bug, pretty-printer, E4, R2, I2, C2

**Comment by hojberg** [comment] 2021-09-09 12:38
Hmm I don't have the original snippet that failed any more i'm afraid, it had more going on than the example I think.
Looks like you got a fix merged 🎉
