### ISSUE TITLE
Unexpected behavior with move.namespace, fork, and merge

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3316] opened 2022-08-12 14:04 UTC
The following assumes that you have pulled these libraries into these namespaces:

```
.> pull unison.public.cloud .cloud
.> pull runarorama.public.codec .codec
```

The `.cloud.lib.codec` namespace accidentally includes all of `codec`, when we really just want the latest release:

```ucm
.> ls cloud.main.lib.codec

  1. releases/ (4151 definitions)
  2. trunk/    (4155 definitions)

```
Let's attempt to replace it with just the release.

```ucm
.> fork .cloud.main .pr.cloud.fixcodec

  Done.

.> cd .pr.cloud.fixcodec

.pr.cloud.fixcodec> move.namespace lib.codec lib.codec_old

  Done.

.pr.cloud.fixcodec> fork .codec.latest lib.codec

  Done.

.pr.cloud.fixcodec> delete.namespace lib.codec_old

  Done.

```
Now in our PR branch everything seems to be as it should be:

```ucm
.pr.cloud.fixcodec> ls lib.codec

  1.  Decode       (type)
  2.  Decode/      (160 definitions)
  3.  DecodeBits   (type)
  4.  DecodeBits/  (99 definitions)
  5.  DecodeError  (type)
  6.  DecodeError/ (10 definitions)
  7.  EncodeBits   (type)
  8.  EncodeBits/  (25 definitions)
  9.  EncodeError  (type)
  10. EncodeError/ (1 definition)
  11. Position     (type)
  12. Position/    (1 definition)
  13. README       (Doc)
  14. README/      (1 definition)
  15. encode/      (39 definitions)
  16. lib/         (3779 definitions)
  17. patch        (patch)
  18. runDecode/   (1 definition)
  19. up/          (26 definitions)
  20. withSocket   (Nat
                   -> Socket
                   -> '{g,
                   EncodeBits,
                   Decode,
                   DecodeBits,
                   Stream Bytes} r
                   ->{g, IO, Exception} r)
  21. withSocket/  (1 definition)

```
But when we merge, we don't get what I would expect:

```ucm
.pr.cloud.fixcodec> cd .cloud.main

.cloud.main> merge .pr.cloud.fixcodec

  Nothing changed as a result of the merge.

.cloud.main> ls lib.codec

  1. releases/ (4151 definitions)
  2. trunk/    (4155 definitions)

```

Why did nothing change as a result of the merge? And why isn't `lib.codec` replaced with the version that I forked there?

**Comment by ChrisPenner** [comment] 2022-08-12 20:26
Unfortunately we don't really have a great way of expressing all of the different possibilities here, I don’t think I have a good enough understanding of how we want to “fix” this in order to implement it right now,

Even looking into causing move.namespace to obliterate history from the ‘src’ this results in some edge cases when you do move.namespace . .somewhere; we can’t do this sort of move with our current branch-editing abstraction if we do a full deletion of history;

Even if we fixed that, it’s a move that wouldn’t be `undo`able using our current undo implementation, since that just pops a branch off of the root history (but that history would now be empty). This also could be fixed or changed I suppose, but let's make sure it's what we want first.

I can implement whatever we want, but I need to know what behaviour I’m implementing :thinking_face: , and want to be confident that it won't just cause another problem in the reverse direction down the line.

I think a lot of these issues would actually be resolved by tracking history at the "project" level rather than at every single namespace, but I also know not everyone agrees with that, and we'd need to dig deeper to ensure there aren't any weird edge cases there too.

**Comment by aryairani** [comment] 2022-08-22 21:38
@ChrisPenner Do you have a hypothesis about what's happening in Cody's case?

**Comment by ChrisPenner** [comment] 2022-08-23 01:48
@aryairani Yes, I worked on this one today: https://github.com/unisonweb/unison/pull/3348, should have time to polish it up tomorrow and I'll test out Cody's reproduction.

**Comment by aryairani** [comment] 2022-08-23 16:22
> Nothing changed as a result of the merge.

> Why did nothing change as a result of the merge? 

I think to directly address this issue, `merge` ought to answer Cody's question.

> And why isn't lib.codec replaced with the version that I forked there?

Chris is gonna dig more deeply into your exact scenario, if an improved message doesn't give us an answer to everything.

**Comment by ChrisPenner** [comment] 2022-08-23 18:09
Okay, so https://github.com/unisonweb/unison/pull/3348 fixes your transcript, which is nice,
but looking into this, I think we have a few bugs (or at least unexpected behaviours) in merge.

Here are a few things I'll look into:

* The merge in this transcript _should_ just be a Fast-forward, since there was a fork, a few changes, then a merge, but it's not being detected as one 🤔 
* the recursive merge ignores any LCA which we may have found on the parents and just does an independent LCA search over the corresponding children at a location, and I'm not yet convinced that it's the correct thing to do 🤔

**Comment by ChrisPenner** [comment] 2022-08-23 18:40
Weird,  it seems `move.namespace lib.codec lib.codec_old` actually _overwrites_ the current causal rather than adding a new cons with the move included, which is wrong, and is making this not a FF change, which also explains why my PR fixes it, though not for the reasons I thought it would.

EDIT:
Yeah, this is a flawed behaviour of the `AllowRewritingHistory` mode of `stepMany`, I think it's much safer to use explicit Branch updates for this sort of thing (Like I do in #3348).

What's happening is that the `AllowRewritingHistory` mode which we use for `move.namespace` and also `pull-request.load` does exactly what it says, and will actually rewrite `Branch`s without squashing them, which is what you want for _child_ branches, but it also rewrites all the parents up to the root, which breaks history in almost every case.

We should instead be more surgical about the changes we want to make. I rewrote `move.namespace`, I'll rewrite `pull-request.load` next and delete the flawed strategy.

**Comment by ChrisPenner** [comment] 2022-08-24 18:08
Fixed in https://github.com/unisonweb/unison/pull/3348

**Closed as completed by ChrisPenner** 2022-08-24 18:08 UTC
