### ISSUE TITLE
Multi-line codeblock syntax roundtrip issue 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#3757] opened 2023-01-19 21:30 UTC
[letBlock.md](https://github.com/unisonweb/unison/files/10461247/letBlock.md)
If you write a compiling multi-line lambda function in a term with `let` to open the codeblock, the UCM will round-trip it without the needed `let` or cases syntax for creating the codeblock. A transcript is attached displaying the issue. 

This term for example, will fail to compile upon editing. 
```
example =
  List.map
    (i -> let
      use Nat +
      x = i + 1
      y = x + 1
      z = y + 1
      z) [1, 2, 3]
```

get's rendered: 
```
example : [Nat]
example =
  use Nat +
  List.map
    (i ->
      x = i + 1
      y = x + 1
      z = y + 1
      z) [1, 2, 3]
```

**Comment by sellout** [comment] 2024-07-09 06:52
Duplicate of #2889.

**Closed as not planned by sellout** 2024-07-09 06:52 UTC
Labels: round-trip

**Comment by sellout** [comment] 2024-07-09 06:55
Sorry, shouldn’t have closed as “completed”.
