### ISSUE TITLE
Pretty-printer produces conflict when function is shadowed by binding

### ISSUE THREAD

**Issue by alvaroc1** [unisonweb/unison#4207] opened 2023-07-18 14:43 UTC
Version: release/M5b

Original code: 

```unison
ticksPerQuarterNote = settings |> SequencerSettings.ticksPerQuarterNote
```

Pretty-printed code (produces type error):

```unison
ticksPerQuarterNote = settings |> ticksPerQuarterNote
```

It doesn't round trip since now the function name conflicts with the binding name.

**Comment by pchiusano** [comment] 2023-07-18 14:53
This one is a dupe of https://github.com/unisonweb/unison/issues/525 which is ancient. I'll take a look at it, I don't think there's any real holdup.

**Closed as completed by pchiusano** 2023-07-18 14:53 UTC
Labels: pretty-printer
