### ISSUE TITLE
fromJust:Nothing when pulling base2

### ISSUE THREAD

**Issue by sullyj3** [unisonweb/unison#1303] opened 2020-03-05 12:54 UTC
```
❯ unison --version
ucm version: release/M2-base-400-gbd81a46e'
```

```
.> pull https://github.com/unisonweb/base2
⚙  git clone --quiet --depth 1 'https://github.com/unisonweb/base2' /home/james/.cache/unisonlanguage/gitfiles/9cihgqbf50khb2lbiopbcvqkrsonpnjm872qt8qi4kv5hakcq3af15vcdrin2mdvooub6l6m7pdtm3i2nslh0kcq0p4kmppdt4al780/HEAD
⚙  git -C /home/james/.cache/unisonlanguage/gitfiles/9cihgqbf50khb2lbiopbcvqkrsonpnjm872qt8qi4kv5hakcq3af15vcdrin2mdvooub6l6m7pdtm3i2nslh0kcq0p4kmppdt4al780/HEAD rev-parse --git-dir
.git
unison: Maybe.fromJust: Nothing
```

Also occurs in m1h

**Comment by sullyj3** [comment] 2020-03-05 12:57
Hmm I may have misunderstood, possibly base is not supposed to work with current master>

**Comment by sullyj3** [comment] 2020-03-05 13:05
Seems like it works fine with a fresh codebase

**Comment by aryairani** [comment] 2020-03-06 02:23
Hm I wonder why.

**Comment by aryairani** [comment] 2020-04-20 01:40
@sullyj3 I'm itching to close this because most of the git code has been or will shortly be rewritten.  Also I can't reproduce in M1i; can you?

**Comment by cflewis** [comment] 2020-04-20 23:07
@aryairani : I am seeing this in M1i. If you want, I am happy to batch up my Unison files for you before blowing them away. Let me know what you need and I'll put them in a tarball (assuming there's no sensitive personally identifiable information of course).

**Comment by aryairani** [comment] 2020-04-20 23:48
@cflewis That would be great.

If you can reproduce the issue with a fresh codebase (`ucm -codebase newdir`) that would presumably end up smaller, and not include any personally identifiable code you may have added.  In that case, just tar up `newdir` and attach it here.

If you can't reproduce it (likely), and if you don't mind sending your primary codebase, it typically lives in `~/.unison`.

Feel free to ping me on Slack if you want to chat about it before uploading.

**Comment by cflewis** [comment] 2020-04-21 00:34
Yes, the `newdir` did work.

I sent @aryairani the `.unison` folder offline :smile:

**Comment by sullyj3** [comment] 2020-04-25 03:22
Yep, I'm getting the same issue in m1i. I'll try m1j.

**Comment by sullyj3** [comment] 2020-04-25 03:31
seems to work fine in m1j. I'm happy for this to be closed if there's nothing further to do

**Closed** 2020-05-03 14:57 UTC
Labels: help wanted
