### ISSUE TITLE
Unexpected successful parse on missing closing list bracket

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#2493] opened 2021-10-13 16:50 UTC
This parses fine, but is definitely missing a closing list bracket.

```unison
xs : [Nat]
xs = ([1, 2, 3)
```

**Comment by pchiusano** [comment] 2021-10-13 17:11
A dupe of: https://github.com/unisonweb/unison/issues/1776 which has some more explanation.

It's a feature!

**Closed as completed by pchiusano** 2021-10-13 17:11 UTC
