### ISSUE TITLE
some commands hang now in my codebase 

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1487] opened 2020-04-29 23:34 UTC
`ucm` hangs when I run some `docs` or `links` commands.

I think this started when I updated a doc, so the term being documented pointed to the previous version.  I've previously seen that cause the `links` command to be slow for that term.  But now it seems to hang for longer than my patience threshold, spin my CPU fan, and refuse to respond to ctrl-C (I have to `kill -9` the process.)

To repro, load the codebase attached, and do `find mersenne.seed` and then `docs 1`.

[codebase.gz](https://github.com/unisonweb/unison/files/4555328/codebase.gz)
[this file is from doing `tar -czvf codebase.gz .unison`]

**Comment by pchiusano** [comment] 2020-04-30 00:37
😕 

This might be same issue as https://github.com/unisonweb/unison/issues/1481

Which current theory is that it’s an issue with the historical name search.

**Comment by aryairani** [comment] 2020-04-30 01:59
Just a heads up — not sure which ticket this belongs on — sometimes the problem can be with the historical name search, and sometimes the problem is with the parameters to the historical name search.  e.g. asking for a type or a term that cannot exist (e.g. because it's actually a term or a type, not a type or term), necessitating a more thorough search than is necessary. /cc #1481

**Comment by runarorama** [comment] 2020-04-30 20:31
Not a duplicate of #1481

**Comment by aryairani** [comment] 2021-06-17 21:02
@atacratic Could you see if this is still reproducible in M2g, and go ahead and close if not?

**Comment by aryairani** [comment] 2021-06-17 21:10
Possibly superseded by #2128

**Comment by runarorama** [comment] 2022-01-13 19:00
I think this is an obsolete issue now that oldNames are no longer a thing.

**Closed by runarorama** 2022-01-13 19:00 UTC
