### ISSUE TITLE
When multiple things match for purposes of TDNR, a type error is reported

### ISSUE THREAD

**Issue by sfultong** [unisonweb/unison#453] opened 2019-04-09 21:05 UTC
Given
```
x = y + 1
y = if x < 5 then x else 5

> x
```

I get 
I'm not sure what < means at line 2, columns 10-11

    2 | y = if x < 5 then x else 5

Whatever it is, it has a type that conforms to Nat -> Nat -> Boolean.

**Comment by pchiusano** [comment] 2019-04-09 21:12
This sounds like just a name resolution thing, there's two `<` in scope and it doesn't know which to use. But I think it should be a different type error - it's a cycle of definitions, none of which are guarded.

This works, but I'm guessing it just happens to work because of Haskell laziness in the runtime. For the real runtime, it should not typecheck, and if you run it without typechecking I'd expect it to bomb.

```haskell
use Universal <

x = y + 1
y = if x < 5 then x else 5

> x
```

**Comment by sfultong** [comment] 2019-04-09 21:39
Note that the type checker also fails to reify sane recursive definitions, like 

```
x n = if n < 5 then y (n + 1) else 5
y n = x n 
```

**Comment by pchiusano** [comment] 2019-04-09 21:59
Going to close this one. This is working as intended. 

Right now there's no rules for selecting among multiple matches (like trying to pick the "most specific") and that route is fraught with peril so going to avoid it. :) So it's expected that when multiple things with the same name all typecheck, you get an error telling you to disambiguate.

```
I'm not sure what < means at line 1, columns 12-13

    1 | x n = if n < 5 then y (n + 1) else 5

Whatever it is, it has a type that conforms to Nat -> Nat -> Boolean.
I found some terms in scope that have matching names and types. Maybe you meant one of these:

  - Universal.< : a -> a -> Boolean
  - Nat.< : Nat -> Nat -> Boolean
```

**Closed by pchiusano** 2019-04-09 21:59 UTC
Labels: actually a feature, bug, unprocessed
