### ISSUE TITLE
ucm: arguments can't be numbers

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#5193] opened 2024-07-08 22:48 UTC
iif you run the `getArgs` builtin all of the numeric args are filtered. so in ucm, run:
```ucm
> run getArgs one 2 three 4 five 6
```
and you only get the odd numbers:
```
["one", "three", "five"]
```

**Comment by ceedubs** [comment] 2024-07-09 13:02
I think that this is the same as #2805 but how it manifests when there are no numbered args saved in the ucm session.

**Comment by aryairani** [comment] 2024-09-24 12:38
#2805 did print the `1` though; are they getting filtered out or are they going in as normal strings? Here they're clearly being filtered out. The fix is the same though.

**Comment by sellout** [comment] 2024-11-27 20:25
Yeah, this is a duplicate of #2805. At some point between then and now, un-assigned numbers started getting filtered.

There is probably a better option (e.g., warn or error on un-assigned numbers), but I think the filtering at least makes more sense than changing the behavior based on whether there are numbered args in the history is just likely to confuse users.

**Closed as not planned by sellout** 2024-11-27 20:25 UTC
Labels: bug, triaged
