### ISSUE TITLE
Patterns (+0, +0) and (a, +0) passed over for (+0, b).

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/unison#2270] opened 2021-07-26 13:53 UTC
I would have expected the `(+0, +0)` case to have been matched.

```
# scratch.u
show : (Int, Int) -> Text
show = cases
  (+0, +0) -> "(+0, +0)"
  (+0, b) -> "(+0, b)"
  (a, +0) -> "(a, +0)"
  (a, b) -> "(a, b)"
> show (+0, +0)

# ucm
    ⍟ These new definitions are ok to `add`:

      show : (Int, Int) -> Text

  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.


    7 | > show (+0, +0)
          ⧩
          "(+0, b)"
```

```
# scratch.u
show : (Int, Int) -> Text
show = cases
  (+0, +0) -> "(+0, +0)"
  (a, +0) -> "(a, +0)"
  (+0, b) -> "(+0, b)"
  (a, b) -> "(a, b)"
> show (+0, +0)

# ucm
    ⍟ These new definitions are ok to `add`:

      show : (Int, Int) -> Text

  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.


    7 | > show (+0, +0)
          ⧩
          "(+0, b)"
```

**Comment by philderbeast** [comment] 2021-08-10 13:42
To reproduce with a transcript:

    > unison transcript.fork 2270.md

[2270.md](https://github.com/unisonweb/unison/files/6962093/2270.md)
[2270.output.md](https://github.com/unisonweb/unison/files/6962094/2270.output.md)

**Comment by stew** [comment] 2022-10-24 18:05
I'm not able to reproduce this one with the current trunk, I suspect that it got fixed somewhere along the way, so I'm going to close this.

**Closed as completed by stew** 2022-10-24 18:05 UTC
