### ISSUE TITLE
Return `Nat`, not `Int` from systemTimeMicroseconds

### ISSUE THREAD

**Issue by benclifford** [unisonweb/unison#2445] opened 2021-09-30 13:35 UTC
Currently (a4627bce8101474242ebd630f85ec54e97ea48b4) systemTimeMicroseconds returns an `Int`:

```
  base.io.systemTimeMicroseconds : '{IO} Int
```

This plays badly with the other microseconds-based function in the base library, which takes a `Nat`:

```
  base.io.delay : Nat ->{IO, Exception} ()
```

**Comment by atacratic** [comment] 2021-09-30 14:26
Rationale for Int is in #2359 . I think actually the issue here is that no changes to base got made to go hand in hand with #2418. Eg EpochTime should switch to Int.

**Comment by alvaroc1** [comment] 2021-09-30 14:34
Yeah, i think we intended for base to just have `systemTime : '{IO} EpochTime` (updated to use the new built-in at the correct resolution), not `systemTimeMicroseconds`. But i forgot to make a PR for base after the built-in got merged.

Maybe the built-in should be `Nat` and the transformation to `EpochTime` (Int) should happen in base, not as part of the built-in?

**Comment by pchiusano** [comment] 2021-09-30 14:46
Going to close this one "as designed". You can do `Int.truncate0 n` to convert an `n : Int` to a `Nat`. It might not be a bad idea to add this to base though -

```
systemTimeMicroseconds.nat : '{IO} Nat
systemTimeMicroseconds.nat _ = truncate0 !systemTimeMicroseconds
```

I agree about `EpochTime` switching to contain an `Int` in base and created https://github.com/unisonweb/base/issues/43 to track that.

**Closed as completed by pchiusano** 2021-09-30 14:46 UTC
