### ISSUE TITLE
punctuation after bold is broken

### ISSUE THREAD

**Issue by dvberkel** [unisonweb/unison#5245] opened 2024-07-23 13:19 UTC
When the following code is added

```unison
boldbug : Doc
boldbug = {{
  The following doc demonstrates the bug.

  {{ Blockquote {{
    If both players cooperate, they both receive the reward *R* for cooperating.
    If both players defect, they both receive the punishment payoff *P*.
    If Blue defects while Red cooperates, then Blue receives the temptation
    payoff *T*, while Red receives the "sucker's" payoff, *S*. Similarly, if
    Blue cooperates while Red defects, then Blue receives the sucker's payoff
    *S*, while Red receives the temptation payoff *T*.
  }}
  }}
}}
```

The closing delimiter of the bold with a trailing punctuation is not correctly parsed.

**Screenshots**
![boldbug](https://github.com/user-attachments/assets/4719a0c0-2df6-469e-883c-fdfcdcf6f798)

**Environment (please complete the following information):**
 - `ucm --version`: unison version: release/0.5.22 (built on 2024-06-13)
 - OS/Architecture: Ubuntu 22.04.4 LTS
 - Browser: Demonstrable both in Firefox 127.0.1 (64-bit) as in Chrome 126.0.6478.126 (Official Build) (64-bit)

**Additional context**
Related to #5091

**Comment by sellout** [comment] 2024-07-25 18:52
Duplicate of #2890. (I just changed the title of that one to make it clearer.)

**Closed as not planned by sellout** 2024-07-25 18:52 UTC
Labels: bug
