### ISSUE TITLE
updating churning for unique types

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1758] opened 2020-11-25 16:28 UTC
ucm should recognize the a new unique type otherwise identical in name and structure to an existing unique type probably has already been added and doesn't need an update.  Currently you can `load` and `update` forever, getting new random keys each time and producing meaningless churn in the namespace history.

Also you can get type mismatches between codebase-only definitions that reference the existing type, and file-only definitions that reference the unintentionally new but otherwise identical unique type in the file.

**Comment by aryairani** [comment] 2021-07-11 21:51
See #2196

**Comment by pchiusano** [comment] 2021-08-23 22:55
Is #2196 just a dupe of this or vice versa? They seem to be talking about the same thing.

**Closed as completed by pchiusano** 2021-08-23 22:55 UTC
Labels: codebase-manager / ucm, dx

**Comment by aryairani** [comment] 2021-08-24 00:20
This one was the problem, #2196 was a proposed solution; forgot to link them though.
