### ISSUE TITLE
"Needs alias" lists both relative and absolute names as "existing"

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#998] opened 2019-11-25 20:42 UTC
```
  I found and typechecked these definitions in scratch.u. If you do an `add` or
  `update`, here's how your codebase would change:

    x These definitions would fail on `add` or `update`:

      Reason
      needs alias   unique type io.Mode   (existing names: .base.io.Mode, base.io.Mode)
```

**Comment by aryairani** [comment] 2019-11-26 00:46
Dupe of #970

**Closed by aryairani** 2019-11-26 00:46 UTC
