### ISSUE TITLE
Doc: linking to () type doesn't work as expected

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4551] opened 2024-01-02 13:40 UTC
In a `Doc` literal, `{type Unit}` seems to properly link to the unit type but `{type ()}` does not (yet still compiles).

```
> {{
  - {type Optional}
  - {type ()}
  - {type Unit}
}}
```

```
          BulletedList
            [ Paragraph [Special (SpecialForm.Link (Left (typeLink Optional)))]
            , Paragraph [Word "{type", Word "()}"]
            , Paragraph [Special (SpecialForm.Link (Left (typeLink Unit)))]
            ]
```

**Comment by alvaroc1** [comment] 2024-01-02 19:25
Duplicate of #2440

**Closed as not planned** 2024-01-03 01:36 UTC
