### ISSUE TITLE
Problem with Big Nat and - operator

### ISSUE THREAD

**Issue by FlorianBELLAZOUZ** [unisonweb/unison#2601] opened 2021-11-05 20:36 UTC
Hi ! 
I notice a problem with Big Nat and the minus operator -

```
Nat.maxNat - 1
           ⧩
           -2    ( expected 18446744073709551614 )
  
Nat.maxNat - 0
           ⧩
           -1    ( expected Nat.maxNat 18446744073709551615 )
``` 

Tested on release/M2j and version 94cbf78

**Comment by atacratic** [comment] 2021-11-05 21:10
Still a problem even after clearing cache?

**Comment by FlorianBELLAZOUZ** [comment] 2021-11-05 21:20
This time yes haha,
You can try it on your side.

**Comment by ceedubs** [comment] 2021-11-05 22:08
`Nat` and `Int` are both 64 bits, right? If so, this seems like an inherent issue with `Nat.-` returning an `Int`. `Int`'s range can't possibly go up to `maxNat` if it also has to represent negative values. Or am I missing something?

**Comment by ceedubs** [comment] 2021-11-05 22:30
@FlorianBELLAZOUZ in case it wasn't clear, my last message wasn't really directed at you 🙂. I'm saying that this seems like an oops in the API, and it's not clear to me how to address it. Thank you very much for finding and reporting this!

**Comment by ceedubs** [comment] 2021-11-05 22:44
From the [language reference](https://www.unisonweb.org/docs/language-reference#literals):

> A 64-bit unsigned integer of type .base.Nat (which stands for natural number) consists of digits from 0 to 9. The smallest Nat is 0 and the largest is 18446744073709551615.
>
> A 64-bit signed integer of type .base.Int consists of a natural number immediately preceded by either + or -. For example, 4 is a Nat, whereas +4 is an Int. The smallest Int is -9223372036854775808 and the largest is +9223372036854775807.

Should `Nat.-` return a `Nat` and have the semantics of truncating at zero of the second nat is bigger? Should it throw a runtime exception like `bug`? Both of these seem bad in different ways.

Maybe this was considered and the idea was that it would be more common to do `5 - 8` and get `-3` than it would be to take a huge `Nat` and subtract a smaller `Nat`?

**Comment by pchiusano** [comment] 2021-11-06 01:32
There's `Nat.drop` which truncates at 0 and returns another `Nat`. That is usually what you want. 

But perhaps we should just rename `Nat.drop` to `Nat.-` and either get rid of `Nat.-` or give it a less prominent name (it can be implemented in terms of `Nat.toInt` which makes clear you're changing the precision).

**Comment by pchiusano** [comment] 2021-11-06 02:16
I kinda think we should close this one "as designed" however I'm open to bikeshedding on the names. :)

Just to document the reasoning a bit more:

* When subtracting nats, you can either a) convert to an `Int` b) truncate at 0, c) throw an exception or d) return an `Optional`/`Either` etc. All are perfectly reasonable things to do, depending on context. We currently have `Nat.-` for converting the result to an `Int`, `Nat.drop` for truncating at 0, and if you want to throw an exception or return `Optional`, you can just do a manual check for that.
* I've found truncation at 0 to be a common desired behavior.
  * If I'm working with values that are possibly negative, I'm using `Int` in the first place and just subtracting ints. If I'm working with `Nat`, it's because negative values don't make sense for the domain - for instance, sizes of things are nicely modeled with nats and truncation at zero reflects that you can't have a negative size for a data structure. 
  * In cases where the subtraction is an exceptional condition, I'm going to be checking for that and producing a more meaningful error, I don't really want the code to just die with an arithmetic exception.

**Comment by FlorianBELLAZOUZ** [comment] 2021-11-06 05:43
If my user point of view matter, I feel the ( b ) truncation at 0 more intuitive for ```Nat.-```

the (a) convert to an Int : trick me because I expect to stay in the Nat domain, and as user if I want to switch to Int I will use the ```Nat.toInt```

the (c) throw an exception  : Like you I don't really want the code to just die with an arithmetic exception

the (d) : as user ( like you said ) I will build manually a function to check that. 

--

In an other hand, maybe ```Nat.toInt``` need :
      (a) to return an ```Optional Int```
      or 
      (b) it may be a need to precise in documentation that if n is between 9223372036854775808 and 18446744073709551615, n will be negative and n => Nat.maxNat - ( n - 1 )

**Comment by ceedubs** [comment] 2022-03-03 03:45
I think that we can mark this as resolved when https://github.com/unisonweb/base/issues/70 makes it into a release.

**Closed as completed** 2022-03-13 17:04 UTC
